### ISSUE TITLE
Why can't I log in to the SPLUNK platform?

### ISSUE THREAD

**Issue by qiukkk** [splunk/docker-splunk#106]
I used the tag is latest .
and use this command "docker run -d -p 8000:8000 -e 'SPLUNK_START_ARGS=--accept-license' -e 'SPLUNK_PASSWORD=<password>' splunk/splunk:latest".
The password has changed to what I know，but I use my password can't log in? what's the problem?
![image](https://user-images.githubusercontent.com/23185029/51441936-06127300-1d12-11e9-9e26-d25c11777c79.png)

**Comment by lephino** [comment]
The container forces UTF-8, and requires the password to be over 8 characters, can you try setting it to something like "MyNewSplunkPassword" and try it again?

**Comment by qiukkk** [comment]
The problem is fixed, it is my problem, I made a very stupid mistake! ! !
