### ISSUE TITLE
Improve security, make SPLUNK_PASSWORD not required

### ISSUE THREAD

**Issue by outcoldman** [splunk/docker-splunk#11]
Exposing password using environment variable not a great idea, especially in case of Splunk for two reasons:

1. `docker inspect` or if you have access to docker API, you can get an administrator password 
2. Every process inside the Splunk container will have access to the admin password. If you install the application from splunkbase with custom code, that custom code can read the admin password and do anything it wants. 
3. I am not sure if that is possible right now out of the box, but I am sure that there is some debug options, that allows you to read environment variables of Splunkd, or maybe SPL command. That means, that you can get access to the admin password.

**Comment by lephino** [comment]
The default.yml exposes the ability to set the password without it being in an env var.  The process to create a default.yml will also auto generate a large random ascii password for you.  This method will not expose the password as env.  The k8 example from @matthewmodestino  does a great job of exposing this file with a stand alone nginx server and pulling from it.  As always with any default setup, I'd strongly recommend you change your password once the instance is up and running.

I'd like more feedback from other people, is it desired for us to start the container in a state with no password?  Is it understand if you do it this way you can't setup clustering?  Would you rather us just randomly generate a default file?

**Comment by outcoldman** [comment]
Just to clarify the issue, this page says that SPLUNK_PASSWORD is required https://github.com/splunk/docker-splunk/blob/master/documentation/ADVANCED.md#valid-enterprise-environment-variables

**Comment by lephino** [comment]
Gotcha; we should make it more clear the field is required, but can be set via env or via a default file.
