### ISSUE TITLE
Allow to install application directly from SplunkBase on start

### ISSUE THREAD

**Issue by outcoldman** [splunk/docker-splunk#14]
Will be very useful to be able to install SplunkBase application by specifying the ID of the app, and some SplunkBase token to be able to download the app on start.

I have received this question a LOT of times for the legacy image. And hoped that new image will be able to support that.

**Comment by lephino** [comment]
This is actually actively being worked on.  Expect it to appear soon!

**Comment by outcoldman** [comment]
@lephino could you please keep this issue open, so people can subscribe for the updates?

**Comment by lephino** [comment]
Reopening for as @outcoldman suggests, we'll close it once the feature is in place.  Please no one else work on this issue, as it's actively being addressed already internal to splunk.

**Comment by nwang92** [comment]
Although I see the use-case for a direct-from-splunkbase install, there's not a clear API on that side to make this feasible. Additionally, Splunkbase requires a login with your Splunk account (as created on www.splunk.com) as well as an license acceptance check. If we wanted to do this as part of the bootstrapping, we would need to expose more secrets/variables/flags.

Would it be feasible for SPLUNK_APPS_URL to be a list of arbitrary URLs that point to the tarballs directly (as discussed here: https://github.com/splunk/docker-splunk/issues/30)? I think this would be more flexible, while also preserving Splunkbase's policy of presenting the license to the end-user and having them agree to it.

**Comment by nwang92** [comment]
Fixed here: https://github.com/splunk/splunk-ansible/pull/8; should be included in the next push of the images.
