### ISSUE TITLE
Splunkd logs should go to stdout

### ISSUE THREAD

**Issue by timoguin** [splunk/docker-splunk#142]
Best practice with containers is to print logs to stdout. Currently the Splunkd logs are sent to a file. For my particular platform (ECS/Fargate), I do not have direct access to the servers or filesystems, which means I can't debug errors that are sent to Splunk's log files. If they were sent to stdout, I would have them available in CloudWatch Logs.

This could be as simple as updating the entrypoint to tail the right log files. For my use case, errors I was getting earlier were being sent to `splunkd.log`

**Comment by lephino** [comment]
Are you sure you want this?  That's one of if not THE most chatty log in splunk.  It could easily blow your cloudwatch logs up in size.  I don't mind adding this, by why not docker cp the log? or just go to splunk and search _internal?  What if we do a tail | grep ERROR or something?  Even as splunk now runs, you don't have anything go to stdout on the main pid on baremetal.  Everything in std_err is logged to a file, would you rather me just tail that?

**Comment by lephino** [comment]
Or thinking more, would you rather me give you a var so you can set what log to tail at the end?

**Comment by nwang92** [comment]
Also to note, I believe splunk internally logs to various files, of which we currently only tail `splunkd_stderr.log`. We could switch to `splunkd.log` if the verbosity isn't a problem, but you may lose insight into failures in other aspects of Splunk (ex. web server, mongo, etc.)

Ideally, the best way to see everything + narrow down the scope of what you're looking for is to run a search `index=_internal` in Splunk :)

**Comment by timoguin** [comment]
In my case particular use case, I received errors in the Web UI about an issue with my IAM role configuration, and the UI tells me to check `splunkd.log`. I'm on Fargate and can't do that. If this log file really is that noisy, then ideally this could be configurable in a few different ways, but this wouldn't be the only service I have with horribly noisy logs (*cough* Jenkins). Log volume is not as much of a concern as the amount of time we spend debugging something.

~I also just did a search on `index=_internal` and got no results. Perhaps it's because I'm only running the Heavy Forwarder? I'm not indexing any forwarded data.~ **Edit:** I just found that the `_internal` index is forwarding to Splunk Cloud as well.

**Comment by matthewmodestino** [comment]
To be clear for those following along, you can search `splunkd.log`, right from the Splunk UI, assuming the  deployed image is successfully forwarding to your indexers (as was the case above), or if it is a standalone instance. (indexed locally)

Splunk forwards/indexes/rotates its internal logs by default, making docker best practices moot as you should not need to access the container filesystem to see your logs.

`index=_internal source=*splunkd.log ERROR OR WARN`

Though, In theory there are cases, especially depending on the instance role, where someone could deploy with broken `outputs.conf`, thus searching in Splunk may not be helpful in a scenario where you can’t exec...

So maybe a flag to turn it on for troubleshooting is the best compromise. Personally, I wouldn’t vote to make it default. I would use docker logs to verify the plays have run and that the image is up, then rely on using Splunk to analyze `_internal`.

**Comment by timoguin** [comment]
I would be happy with a flag to assist with troubleshooting. It looks like tailing more than one file is doable. I would like to be able to grab all the log files that could help with debugging.

**Comment by nwang92** [comment]
Added a new env var to control this behavior here: https://github.com/splunk/docker-splunk/pull/163.

This should be released in the next version bump of images (7.2.6), pending mid-April.
