### ISSUE TITLE
Failed to set permissions 

### ISSUE THREAD

**Issue by mrw5641** [splunk/docker-splunk#143]
Hi -- running the  below and getting an issue with permissions

docker run -d -p 8000:8000 -e 'SPLUNK_START_ARGS=--accept-license' -e 'SPLUNK_PAS                SWORD=XXXXXX' splunk/splunk:latest

docker logs 85c5235956ae

PLAY [Run default Splunk provisioning] *****************************************
Thursday 07 March 2019  13:19:26 +0000 (0:00:00.074)       0:00:00.074 ********

TASK [Gathering Facts] *********************************************************
fatal: [localhost]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create w                hen becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1551964766.48-23                6620129376040/': Operation not permitted\nchown: changing ownership of '/var/tmp/ansible-tmp-1551964766.48-2366201                29376040/AnsiballZ_setup.py': Operation not permitted\n}). For information on working around this, see https://doc                s.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
        to retry, use: --limit @/opt/container_artifact/ansible-retry/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

**Comment by nwang92** [comment]
Can you verify if this is the issue you're facing? https://github.com/splunk/docker-splunk/issues/105

**Comment by arctan5x** [comment]
@mrw5641 Since it has been almost a month. Closing this issue for now. If you have an update after following through https://github.com/splunk/docker-splunk/issues/105, please reopen the issue.
