### ISSUE TITLE
Universal Forwarder - UF install shouldn't be done by an Entrypoint

### ISSUE THREAD

**Issue by dcruzin** [splunk/docker-splunk#144]
Universal Forwarder is supposed to be a lightweight app. Why should I need Ansible inside my container? UF is relativy easy to spin up. It doesn't need playbooks.

Also, I would like to be able to use splunk/universalforwarder as a base image, with my own set of Entrypoints.

Finally, debugging this image is a bit harder, especially if you are used to see all image setup on a Dockerfile (as it should be!).

I know you guys like Ansible, but this is such an overkill :)

**Comment by mikedickey** [comment]
UF is basically full Splunk, just without the UI. All of its configuration is managed the same, via disk files in etc. While future generations of UF may be different, at this time an entrypoint is required to provide any configuration-at-runtime capabilities. And while this may not be strictly required for trivial scenarios, most configurations that we run into require it.

**Comment by dcruzin** [comment]
Is there any docker configuration that requires a playbook called "Check if we are in docker" or "Check for existing installation"?

This doesn't make sense. Clearly, those playbooks were migrated from somewhere else and attached to this image in the fastest way possible -> entrypoint.

Correct me if I'm wrong, but every playbook in the UF context can be translated into a Dockerfile using the CMD syntax. It's not even that hard!

Not sure why this is marked as "Closed" too.
