### ISSUE TITLE
Silent failure on building a docker container with a password that doesn't conform to the default requirements

### ISSUE THREAD

**Issue by MiaMish** [splunk/docker-splunk#15]
Apparently, if you use a password that doesn't conform to the default authentication prefernces, the docker image will start up just fine, no errors or warnings, but client login will fail with error 401 "No users exist. Please set up a user."

So couple of issues:

- The password requirement is only documented in dockerhub (https://hub.docker.com/r/splunk/splunk/), but not in github, and could be more detailed.

- Docker should not start up without any warning logs if admin account failed to be created.

For full commands and logs, see the Stackoverflow question I opened:

https://stackoverflow.com/questions/52689758/deploying-splunk-docker-image-fails-to-login/52696725#52696725

**Comment by lephino** [comment]
@arctan5x since you have a related bug with passwords, wanna tackle this one too?

**Comment by arctan5x** [comment]
Got it.

**Comment by arctan5x** [comment]
1) I have made the documentation highlight the password requirement

2) When in debug mode, there will be a warning message in stdout about a password that does not meet the requirement.
