### ISSUE TITLE
CPU core count is misreported

### ISSUE THREAD

**Issue by abshkd** [splunk/docker-splunk#153]
![cpu_count](https://user-images.githubusercontent.com/771356/54889953-0847a800-4ee2-11e9-8757-b94ef035cd84.JPG)
The actual CPU count is 32. 

I have not changed default docker settings and it should be reporting all cores.

**Comment by mikedickey** [comment]
Are you running this on a Linux host machine or using "Docker for (Mac/Windows)" ? What do you get when running this?

`docker run --rm -it alpine sh -c 'nproc && cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us && cat /sys/fs/cgroup/cpu/cpu.cfs_period_us'`

**Comment by abshkd** [comment]
linux
output from command
```
64
-1
100000
```

**Comment by nwang92** [comment]
I don't think splunkd is container aware, and thus it's reporting everything on the host that it's running on. However, any reservations/requests/limits will still be honored by the scheduler.

This is more of a product change, but I'll file a ticket internally to see if there's something we can do about this.
