### ISSUE TITLE
Docs table for exposed ports

### ISSUE THREAD

**Issue by halr9000** [splunk/docker-splunk#159]
I'd like to see a mention in the docs (perhaps under setup or advanced) that explains the purpose of each of the exposed ports listed in the dockerfile. Seasoned Splunkers will recognize several (8000, 9997), but there are some that are not clear at all. I think having this in one place would be helpful.

**Comment by arctan5x** [comment]
https://github.com/splunk/docker-splunk/pull/162 Resolves this ticket. Closing.
