### ISSUE TITLE
splunk:http_port in default.yml ignored

### ISSUE THREAD

**Issue by gibban69** [splunk/docker-splunk#179]
Trying to enable ssl in web.conf on port 8888 but http_port seems to be ignored.
The command 

    docker run --rm -it splunk/splunk:latest create-defaults > default.yml

generates a **default.yml** including this config:

    splunk:
      http_enableSSL: 0
      http_enableSSL_cert: null
      http_enableSSL_privKey: null
      http_enableSSL_privKey_password: null
      http_port: 8000

Since that config file is auto generated, one tend to believe that all parameters in it can be changed to be used for generating a new config. However, changing config to:

    splunk:
      http_enableSSL: 1
      http_enableSSL_cert: /ssl/host.crt
      http_enableSSL_privKey: /ssl/host.key.nopass
      http_enableSSL_privKey_password: null
      http_port: 8888

generates this file **/opt/splunk/etc/system/local/web.conf** containing:

    [settings]
    enableSplunkWebSSL = True
    serverCert = /ssl/host.crt
    privKeyPath = /ssl/host.key.nopass

http_port: 8888 is ignored.

I think the problem might be in this file:

    https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_common/tasks/enable_ssl_on_gui.yml

**Comment by BertieW** [comment]
I raised an issue around this in the splunk-ansible repo as well. 

https://github.com/splunk/splunk-ansible/issues/140

**Comment by BertieW** [comment]
The issue has been resolved in the ansible splunk repo I think it is just a matter of waiting for it to be built into the container.

**Comment by nwang92** [comment]
We'll be pushing out a new release early next week which should incorporate this change. In the meantime, if you're using `splunk/splunk:edge` it should be in there.

I'm going to close this, but please feel free to reopen if you continue to see problems.
