### ISSUE TITLE
Unprivileged splunk docker image

### ISSUE THREAD

**Issue by ghantakiran** [splunk/docker-splunk#184]
Any insights in creating an unprivileged Splunk docker image, as I have a customer who has restrictions deploying containers with root access. Any insights will be appreciated.

**Comment by abshkd** [comment]
I had a similar issue see #118

**Comment by mikedickey** [comment]
Please see https://github.com/splunk/docker-splunk/pull/222

**Comment by mikedickey** [comment]
Resolved by https://github.com/splunk/docker-splunk/pull/222. Please see https://github.com/splunk/docker-splunk/blob/develop/docs/SECURITY.md for more info.
