### ISSUE TITLE
Snapshots not working

### ISSUE THREAD

**Issue by kurktchiev** [splunk/docker-splunk#187]
Every time I install the kube 3idxc3shc1cm1lm1dep-pvc example. The search heads all throw the following error when and have the red flag against Snapshot Creation. Not sure how to fix it.

05-16-2019 19:44:19.834 +0000 WARN ConfReplication - downloadDeployableApps: Error listing baseline configuration: Non-200/201 status_code=401; {"messages":[{"type":"ERROR","text":"Unauthorized"}]}

**Comment by yamila123** [comment]
Hi Boris - How did you resolve the above issue?

**Comment by lukasz1992** [comment]
I have the same problem
@yamila123 did you manage to make it work?
