### ISSUE TITLE
Expand supported runtimes

### ISSUE THREAD

**Issue by outcoldman** [splunk/docker-splunk#19]
In the docs you say that only Docker starting from 17.x is supported.

That leaves a question for support of Kubernetes and OpenShift, where their recommended docker runtime is 1.13.1, see https://github.com/splunk/docker-splunk/blob/master/documentation/SETUP.md#supported-docker-engine-versions

And for Kubernetes, they can use different runtimes, not only Docker https://kubernetes.io/docs/setup/independent/install-kubeadm/#installing-runtime, line cri-o, containerd, etc. They all compatible with Docker image.

**Comment by mikedickey** [comment]
Docker 1.13.1 is over 18 months old, which in the world of containerization is ancient. We run very large scale container clusters at Splunk, and know from experience that older versions of the engine and Linux kernel have severe stability and performance problems that we hope our customers can avoid.

While other runtimes should (in theory) work fine, this is still an early effort so we need to keep the support matrix small and limited to what we're currently able to test with. If you have specific needs, please reach out to your sales representative. Over time, demand from our customers will help drive support for additional runtimes.
