### ISSUE TITLE
Please update the Installing Splunk Apps and Add-ons page

### ISSUE THREAD

**Issue by pinterl** [splunk/docker-splunk#210]
A link in the Splunk Docker documentation took me to
https://splunk.github.io/docker-splunk/advanced/APP_INSTALL.html#splunkbase-apps

The page has lots of great information, please update the page when you have time:

The 'Multiple apps' link returns 404
The 'Apps in distributed environments' link does not go anywhere
The 'docker-compose.yml' code snippet examples at the bottom of the page are not correctly formatted and lots of information is hidden. The code is only visible in "view source" mode.

**Comment by nwang92** [comment]
Should be fixed here: https://github.com/splunk/docker-splunk/pull/280
