### ISSUE TITLE
why can't i log in to Splunk?

### ISSUE THREAD

**Issue by Firebass** [splunk/docker-splunk#219]
Hello, i installed Splunk on an Container on Debian but somehow i can't log in??
![grafik](https://user-images.githubusercontent.com/49242474/62538794-fabd0a00-b853-11e9-9d74-11cccc571b37.png)
i use my PassWD "MyNewSplunkPassword" and user "admin" but it won't work.
![grafik](https://user-images.githubusercontent.com/49242474/62538877-250ec780-b854-11e9-87a9-b88351fc8e4d.png)

**Comment by matthewmodestino** [comment]
You left the brackets in your password.

With the above command your password is literally`<MyNewSplunkPassword>`

**Comment by Firebass** [comment]
Oh LOL Thanks :'D
