### ISSUE TITLE
No Argument to enable SSL WebGUI

### ISSUE THREAD

**Issue by PrymalInstynct** [splunk/docker-splunk#223]
I have been unable to create an SSL enabled WebGUI on a Heavy Forwarder container from the point of deployment. I noticed that there is an splunk-ansible [playbook](https://github.com/splunk/splunk-ansible/blob/08baad3a233d6c65f2d90f4d90950f85b4d00ad0/roles/splunk_common/tasks/enable_ssl_on_gui.yml) to enable HTTPS but there is no argument to turn it do do when deploying a container. This seems like a capability that should always been enabled on a splunk deployment that isn't present in the deployment arguments.

**Comment by nwang92** [comment]
We have some automation that runs a test with SSL enabled on the web UI for standalone Splunk instances: https://github.com/splunk/docker-splunk/blob/develop/tests/test_docker_splunk.py#L1090

I suppose we haven't tested this on the heavy forwarder role specifically, but it should work if you follow the correct `docker run ...` environment variables and parameters (and by providing your own SSL certs as well).

**Comment by PrymalInstynct** [comment]
Ok, great I will test this out. Maybe get it added somewhere in the documentation that this in a valid environment argument.
