### ISSUE TITLE
Trying to provision kubernetes splunk fails on create ui login

### ISSUE THREAD

**Issue by modevops** [splunk/docker-splunk#228]
master container continuously restarting and is failing at 2019-09-02T19:18:21.829182823Z TASK [splunk_common : Create .ui_login] ****************************************
2019-09-02T19:18:21.829753967Z fatal: [localhost]: FAILED! => {"changed": false, "checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "msg": "Source /var/tmp/ansible-tmp-1567451901.53-126113864975833/source not found"}

ansible-playbook 2.8.3
  config file = /opt/ansible/ansible.cfg
  configured module search path = [u'/opt/ansible/library', u'/opt/ansible/apps/library', u'/opt/ansible/ansible_commands']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]
{
    "_meta": {
        "hostvars": {
            "localhost": {
                "ansible_connection": "local"
            }
        }
    }, 
    "all": {
        "children": [
            "ungrouped"
        ], 
        "hosts": [
            "localhost"
        ], 
        "vars": {
            "ansible_post_tasks": null, 
            "ansible_pre_tasks": null, 
            "ansible_ssh_user": "splunk", 
            "cert_prefix": "https", 
            "config": {
                "baked": "default.yml", 
                "defaults_dir": "/tmp/defaults", 
                "env": {
                    "headers": null, 
                    "var": "SPLUNK_DEFAULTS_URL", 
                    "verify": true
                }, 
                "host": {
                    "headers": null, 
                    "url": null, 
                    "verify": true
                }, 
                "max_delay": 60, 
                "max_retries": 3, 
                "max_timeout": 1200
            }, 
            "delay_num": 3, 
            "docker_version": "18.06.0", 
            "hide_password": false, 
            "retry_num": 50, 
            "shc_bootstrap_delay": 30, 
            "splunk": {
                "admin_user": "admin", 
                "allow_upgrade": true, 
                "app_paths": {
                    "default": "/opt/splunk/etc/apps", 
                    "deployment": "/opt/splunk/etc/deployment-apps", 
                    "httpinput": "/opt/splunk/etc/apps/splunk_httpinput", 
                    "idxc": "/opt/splunk/etc/master-apps", 
                    "shc": "/opt/splunk/etc/shcluster/apps"
                }, 
                "apps_location": [], 
                "build_location": null, 
                "build_remote_src": false, 
                "deployer_included": false, 
                "enable_service": false, 
                "exec": "/opt/splunk/bin/splunk", 
                "group": "splunk", 
                "hec_disabled": 0, 
                "hec_enableSSL": 1, 
                "hec_port": 8088, 
                "hec_token": "fc8a55bd-edb2-4317-823e-3ab178f94c2c", 
                "home": "/opt/splunk", 
                "http_enableSSL": 0, 
                "http_enableSSL_cert": null, 
                "http_enableSSL_privKey": null, 
                "http_enableSSL_privKey_password": null, 
                "http_port": 8000, 
                "idxc": {
                    "enable": false, 
                    "label": "idxc_label", 
                    "replication_factor": 3, 
                    "replication_port": 9887, 
                    "search_factor": 3, 
                    "secret": "**************"
                }, 
                "ignore_license": false, 
                "indexer_cluster": true, 
                "license_download_dest": "/tmp/splunk.lic", 
                "license_master_included": false, 
                "license_uri": "splunk.lic", 
                "multisite_replication_factor_origin": 3, 
                "multisite_replication_factor_total": 3, 
                "multisite_search_factor_origin": 3, 
                "multisite_search_factor_total": 3, 
                "nfr_license": "/tmp/nfr_enterprise.lic", 
                "opt": "/opt", 
                "password": "**************", 
                "pid": "/opt/splunk/var/run/splunk/splunkd.pid", 
                "role": "splunk_cluster_master", 
                "root_endpoint": null, 
                "s2s_enable": true, 
                "s2s_port": 9997, 
                "search_head_cluster": false, 
                "search_head_cluster_url": null, 
                "secret": null, 
                "shc": {
                    "enable": false, 
                    "label": "shc_label", 
                    "replication_factor": 3, 
                    "replication_port": 9887, 
                    "secret": "**************"
                }, 
                "smartstore": null, 
                "svc_port": 8089, 
                "tar_dir": "splunk", 
                "user": "splunk", 
                "wildcard_license": false
            }, 
            "splunk_home_ownership_enforcement": true
        }
    }, 
    "splunk_cluster_master": {
        "hosts": [
            "master"
        ]
    }, 
    "splunk_indexer": {
        "hosts": [
            "indexer-0", 
            "indexer-1", 
            "indexer-2"
        ]
    }, 
    "splunk_search_head": {
        "hosts": [
            "search"
        ]
    }, 
    "ungrouped": {
        "hosts": []
    }
}

PLAY [Run default Splunk provisioning] *****************************************
Monday 02 September 2019  19:22:09 +0000 (0:00:00.025)       0:00:00.025 ****** 

TASK [Gathering Facts] *********************************************************
[0;32mok: [localhost][0m
Monday 02 September 2019  19:22:10 +0000 (0:00:01.210)       0:00:01.235 ****** 
Monday 02 September 2019  19:22:10 +0000 (0:00:00.033)       0:00:01.268 ****** 
Monday 02 September 2019  19:22:10 +0000 (0:00:00.032)       0:00:01.301 ****** 
Monday 02 September 2019  19:22:10 +0000 (0:00:00.106)       0:00:01.407 ****** 
[0;36mincluded: /opt/ansible/roles/splunk_common/tasks/get_facts.yml for localhost[0m
Monday 02 September 2019  19:22:10 +0000 (0:00:00.046)       0:00:01.454 ****** 

TASK [splunk_common : Set privilege escalation user] ***************************
[0;32mok: [localhost][0m
Monday 02 September 2019  19:22:10 +0000 (0:00:00.026)       0:00:01.480 ****** 

TASK [splunk_common : Check for existing installation] *************************
[0;32mok: [localhost][0m
Monday 02 September 2019  19:22:11 +0000 (0:00:00.449)       0:00:01.930 ****** 

TASK [splunk_common : Set splunk install fact] *********************************
[0;32mok: [localhost][0m
Monday 02 September 2019  19:22:11 +0000 (0:00:00.023)       0:00:01.954 ****** 

TASK [splunk_common : Check for existing splunk secret] ************************
[0;32mok: [localhost][0m
Monday 02 September 2019  19:22:11 +0000 (0:00:00.093)       0:00:02.048 ****** 

TASK [splunk_common : Set first run fact] **************************************
[0;32mok: [localhost][0m
Monday 02 September 2019  19:22:11 +0000 (0:00:00.028)       0:00:02.076 ****** 

TASK [splunk_common : Check if we are in a docker] *****************************
[0;32mok: [localhost][0m
Monday 02 September 2019  19:22:11 +0000 (0:00:00.315)       0:00:02.392 ****** 

TASK [splunk_common : Set docker fact] *****************************************
[0;32mok: [localhost][0m
Monday 02 September 2019  19:22:11 +0000 (0:00:00.028)       0:00:02.421 ****** 
Monday 02 September 2019  19:22:11 +0000 (0:00:00.025)       0:00:02.446 ****** 

TASK [splunk_common : Find manifests] ******************************************
[0;32mok: [localhost][0m
Monday 02 September 2019  19:22:11 +0000 (0:00:00.236)       0:00:02.682 ****** 

TASK [splunk_common : Set current version fact] ********************************
[0;32mok: [localhost][0m
Monday 02 September 2019  19:22:11 +0000 (0:00:00.029)       0:00:02.711 ****** 

TASK [splunk_common : Setting upgrade fact] ************************************
[0;32mok: [localhost][0m
Monday 02 September 2019  19:22:11 +0000 (0:00:00.027)       0:00:02.739 ****** 
[0;36mincluded: /opt/ansible/roles/splunk_common/tasks/change_splunk_directory_owner.yml for localhost[0m
Monday 02 September 2019  19:22:11 +0000 (0:00:00.049)       0:00:02.788 ****** 

TASK [splunk_common : Update Splunk directory owner] ***************************
[0;32mok: [localhost][0m
Monday 02 September 2019  19:22:12 +0000 (0:00:00.947)       0:00:03.735 ****** 
[0;36mincluded: /opt/ansible/roles/splunk_common/tasks/update_etc.yml for localhost[0m
Monday 02 September 2019  19:22:12 +0000 (0:00:00.049)       0:00:03.785 ****** 

TASK [splunk_common : Check if /sbin/updateetc.sh exists] **********************
[0;32mok: [localhost][0m
Monday 02 September 2019  19:22:13 +0000 (0:00:00.356)       0:00:04.142 ****** 

TASK [splunk_common : Update /opt/splunk/etc] **********************************
[0;33mchanged: [localhost][0m
Monday 02 September 2019  19:22:13 +0000 (0:00:00.446)       0:00:04.588 ****** 
Monday 02 September 2019  19:22:13 +0000 (0:00:00.024)       0:00:04.612 ****** 
Monday 02 September 2019  19:22:13 +0000 (0:00:00.025)       0:00:04.638 ****** 
Monday 02 September 2019  19:22:13 +0000 (0:00:00.030)       0:00:04.669 ****** 
[0;36mincluded: /opt/ansible/roles/splunk_common/tasks/remove_first_login.yml for localhost[0m
Monday 02 September 2019  19:22:13 +0000 (0:00:00.058)       0:00:04.727 ****** 

TASK [splunk_common : Create .ui_login] ****************************************
[0;31mfatal: [localhost]: FAILED! => {"changed": false, "checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "msg": "Source /var/tmp/ansible-tmp-1567452133.91-22207983903786/source not found"}[0m

PLAY RECAP *********************************************************************
[0;31mlocalhost[0m                  : [0;32mok=18  [0m [0;33mchanged=1   [0m unreachable=0    [0;31mfailed=1   [0m [0;36mskipped=6   [0m rescued=0    ignored=0   

Monday 02 September 2019  19:22:14 +0000 (0:00:00.318)       0:00:05.046 ****** 
=============================================================================== 
Gathering Facts --------------------------------------------------------- 1.21s
splunk_common : Update Splunk directory owner --------------------------- 0.95s
splunk_common : Check for existing installation ------------------------- 0.45s
splunk_common : Update /opt/splunk/etc ---------------------------------- 0.45s
splunk_common : Check if /sbin/updateetc.sh exists ---------------------- 0.36s
splunk_common : Create .ui_login ---------------------------------------- 0.32s
splunk_common : Check if we are in a docker ----------------------------- 0.32s
splunk_common : Find manifests ------------------------------------------ 0.24s
Provision role ---------------------------------------------------------- 0.11s
splunk_common : Check for existing splunk secret ------------------------ 0.09s
splunk_common : include_tasks ------------------------------------------- 0.06s
splunk_common : include_tasks ------------------------------------------- 0.05s
splunk_common : include_tasks ------------------------------------------- 0.05s
splunk_common : include_tasks ------------------------------------------- 0.05s
Determine captaincy ----------------------------------------------------- 0.03s
Execute pre-setup playbooks --------------------------------------------- 0.03s
splunk_common : Upgrade Splunk ------------------------------------------ 0.03s
splunk_common : Set current version fact -------------------------------- 0.03s
splunk_common : Set docker fact ----------------------------------------- 0.03s
splunk_common : Set first run fact -------------------------------------- 0.03s
splunkd is not running.

**Comment by arctan5x** [comment]
Seems like password is missing. Are you passing in an env var "SPLUNK_PASSWORD"?

**Comment by modevops** [comment]
here is my deployment yaml and password is there {
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "master",
    "namespace": "splunk",
    "selfLink": "/apis/extensions/v1beta1/namespaces/splunk/deployments/master",
    "uid": "0f4a2992-d245-11e9-a771-025bc0ee750a",
    "resourceVersion": "727652",
    "generation": 1,
    "creationTimestamp": "2019-09-08T14:29:26Z",
    "labels": {
      "app": "splunk",
      "role": "splunk_cluster_master",
      "tier": "management"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "1",
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"splunk\",\"role\":\"splunk_cluster_master\",\"tier\":\"management\"},\"name\":\"master\",\"namespace\":\"splunk\"},\"spec\":{\"replicas\":1,\"template\":{\"metadata\":{\"labels\":{\"app\":\"splunk\",\"role\":\"splunk_cluster_master\",\"tier\":\"management\"}},\"spec\":{\"containers\":[{\"env\":[{\"name\":\"SPLUNK_HOME\",\"value\":\"/opt/splunk\"},{\"name\":\"SPLUNK_DEFAULTS_URL\",\"value\":\"http://splunk-defaults/default.yml\"},{\"name\":\"SPLUNK_ROLE\",\"value\":\"splunk_cluster_master\"},{\"name\":\"SPLUNK_PASSWORD\",\"value\":\"helloworld\"},{\"name\":\"SPLUNK_START_ARGS\",\"value\":\"--accept-license\"},{\"name\":\"SPLUNK_CLUSTER_MASTER_URL\",\"value\":\"master\"},{\"name\":\"SPLUNK_INDEXER_URL\",\"value\":\"indexer-0,indexer-1,indexer-2\"},{\"name\":\"SPLUNK_SEARCH_HEAD_URL\",\"value\":\"search\"},{\"name\":\"DEBUG\",\"value\":\"true\"}],\"image\":\"splunk/splunk:latest\",\"name\":\"master\",\"ports\":[{\"containerPort\":8000,\"name\":\"web\"},{\"containerPort\":8089,\"name\":\"mgmt\"},{\"containerPort\":8191,\"name\":\"kv\"}],\"volumeMounts\":[{\"mountPath\":\"/opt/splunk/var\",\"name\":\"splunk-master-data\"},{\"mountPath\":\"/opt/splunk/etc\",\"name\":\"splunk-master-config\"}]}],\"dnsConfig\":{\"searches\":[\"indexer.splunk.svc.cluster.local\"]},\"dnsPolicy\":\"ClusterFirst\",\"hostname\":\"master\",\"volumes\":[{\"emptyDir\":{},\"name\":\"splunk-master-config\"},{\"emptyDir\":{},\"name\":\"splunk-master-data\"}]}}}}\n"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "splunk",
        "role": "splunk_cluster_master",
        "tier": "management"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "splunk",
          "role": "splunk_cluster_master",
          "tier": "management"
        }
      },
      "spec": {
        "volumes": [
          {
            "name": "splunk-master-config",
            "emptyDir": {}
          },
          {
            "name": "splunk-master-data",
            "emptyDir": {}
          }
        ],
        "containers": [
          {
            "name": "master",
            "image": "splunk/splunk:latest",
            "ports": [
              {
                "name": "web",
                "containerPort": 8000,
                "protocol": "TCP"
              },
              {
                "name": "mgmt",
                "containerPort": 8089,
                "protocol": "TCP"
              },
              {
                "name": "kv",
                "containerPort": 8191,
                "protocol": "TCP"
              }
            ],
            "env": [
              {
                "name": "SPLUNK_HOME",
                "value": "/opt/splunk"
              },
              {
                "name": "SPLUNK_DEFAULTS_URL",
                "value": "http://splunk-defaults/default.yml"
              },
              {
                "name": "SPLUNK_ROLE",
                "value": "splunk_cluster_master"
              },
              {
                "name": "SPLUNK_PASSWORD",
                "value": "helloworld"
              },
              {
                "name": "SPLUNK_START_ARGS",
                "value": "--accept-license"
              },
              {
                "name": "SPLUNK_CLUSTER_MASTER_URL",
                "value": "master"
              },
              {
                "name": "SPLUNK_INDEXER_URL",
                "value": "indexer-0,indexer-1,indexer-2"
              },
              {
                "name": "SPLUNK_SEARCH_HEAD_URL",
                "value": "search"
              },
              {
                "name": "DEBUG",
                "value": "true"
              }
            ],
            "resources": {},
            "volumeMounts": [
              {
                "name": "splunk-master-data",
                "mountPath": "/opt/splunk/var"
              },
              {
                "name": "splunk-master-config",
                "mountPath": "/opt/splunk/etc"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "hostname": "master",
        "schedulerName": "default-scheduler",
        "dnsConfig": {
          "searches": [
            "indexer.splunk.svc.cluster.local"
          ]
        }
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": 1,
        "maxSurge": 1
      }
    },
    "revisionHistoryLimit": 2147483647,
    "progressDeadlineSeconds": 2147483647
  },
  "status": {
    "observedGeneration": 1,
    "replicas": 1,
    "updatedReplicas": 1,
    "unavailableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2019-09-08T14:29:26Z",
        "lastTransitionTime": "2019-09-08T14:29:26Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      }
    ]
  }
}

**Comment by modevops** [comment]
this is my default.yaml 
---
ansible_post_tasks: null
ansible_pre_tasks: null
cert_prefix: https
config:
  baked: default.yml
  defaults_dir: /tmp/defaults
  env:
    headers: null
    var: SPLUNK_DEFAULTS_URL
    verify: true
  host:
    headers: null
    url: null
    verify: true
  max_delay: 60
  max_retries: 3
  max_timeout: 1200
hide_password: false
retry_num: 50
shc_bootstrap_delay: 30
splunk:
  admin_user: admin
  allow_upgrade: true
  app_paths:
    default: /opt/splunk/etc/apps
    deployment: /opt/splunk/etc/deployment-apps
    httpinput: /opt/splunk/etc/apps/splunk_httpinput
    idxc: /opt/splunk/etc/master-apps
    shc: /opt/splunk/etc/shcluster/apps
  enable_service: false
  exec: /opt/splunk/bin/splunk
  group: splunk
  hec_disabled: 0
  hec_enableSSL: 1
  hec_port: 8088
  hec_token: 462acb8d-59d1-4095-b7ec-be24388e2b28
  home: /opt/splunk
  http_enableSSL: 0
  http_enableSSL_cert: null
  http_enableSSL_privKey: null
  http_enableSSL_privKey_password: null
  http_port: 8000
  idxc:
    enable: false
    label: idxc_label
    replication_factor: 3
    replication_port: 9887
    search_factor: 3
    secret: gfW3pw/9nZ+Jipn3JmEi1ozNIGI06Pni
  ignore_license: false
  license_download_dest: /tmp/splunk.lic
  multisite_replication_factor_origin: 3
  multisite_replication_factor_total: 3
  multisite_search_factor_origin: 3
  multisite_search_factor_total: 3
  nfr_license: /tmp/nfr_enterprise.lic
  opt: /opt
  password: vjyG4zcQENCTJyQEn+l6ru+6OHjNqoeC
  pid: /opt/splunk/var/run/splunk/splunkd.pid
  root_endpoint: null
  s2s_enable: true
  s2s_port: 9997
  search_head_cluster_url: null
  secret: null
  shc:
    enable: false
    label: shc_label
    replication_factor: 3
    replication_port: 9887
    secret: 0WoIxfVPNSsnB3+Hs7/Dk5//JLPiRlrT
  smartstore: null
  svc_port: 8089
  tar_dir: splunk
  user: splunk
  wildcard_license: false
splunk_home_ownership_enforcement: true

**Comment by jmeixensperger** [comment]
@jonathan-vega-splunk this looks similar to the issue we were seeing on the new ucp cluster. I believe this is a [splunk-ansible](https://github.com/splunk/splunk-ansible) issue that needs to be fixed.

**Comment by nwang92** [comment]
I believe this is addressed with https://github.com/splunk/splunk-ansible/pull/255/files so I'm tentatively closing this for now. We published `splunk/splunk:7.2.8` with this change, so please let me know if this looks fixed. Otherwise, feel free to re-open this issue.
