### ISSUE TITLE
Need Docker container environment variables for the Deployment Server ports

### ISSUE THREAD

**Issue by ghost** [splunk/docker-splunk#23]
If I specify a port on the host defined in the SPLUNK_DEPLOYMENT_SERVER environment variable passed to the Splunk Universal Forwarder docker container I get the error below.

**fatal: [localhost]: FAILED! => {"attempts": 50, "changed": true, "cmd": ["/opt/splunkforwarder/bin/splunk", "set", "deploy-poll", "splunk-enterprise:8089:9997", "-auth", "admin:dKpNH4hB5bKvDB"], "delta": "0:00:00.454031", "end": "2018-10-08 19:32:07.967105", "msg": "non-zero return code", "rc": 22, "start": "2018-10-08 19:32:07.513074", "stderr": "Invalid host and/or port given, targetUri=splunk-enterprise:8089:9997", "stderr_lines": ["Invalid host and/or port given, targetUri=splunk-enterprise:8089:9997"], "stdout": "", "stdout_lines": []}**

Appears that the Splunk Forwarded appends **:9997** to the variable value. 
If I don't specify the port, the Splunk Universal Forwarder connects fine to the Splunk Deployment Server. 

I exchanged an email with Brian Bingham (@lephino) from Splunk.  His response:

There are 2 major vars for ports: s2s_port and svc_port.  To specify them you should pass in a defaults file that overrides them (in the advanced.md section).  We could expose these to env vars if it’s easier than the default file.  

Yes, environment variables are needed and would make the deployment easier.

My docker-compose.yaml file which defines the Splunk Forwarder service.

splunk-forwarder:
    image: splunk/universalforwarder:latest
    hostname: splunk-forwarder
    depends_on:
      - splunk-enterprise
    networks:
      - splunk-backend
    deploy:
        mode: global
    ports:
      - "1514:1514"
      - "9997:9997"
    environment:
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=Hidden
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_FORWARD_SERVER='splunk-enterprise:9997'
      - SPLUNK_FORWARD_SERVER_ARGS=-method clone
      - SPLUNK_ADD_1=tcp 1514 -sourcetype syslog
      - SPLUNK_DEPLOYMENT_SERVER='splunk-enterprise:8089'
    volumes:
      - splunk-forwarder-etc:/opt/splunk/etc
      - splunk-forwarder-var:/opt/splunk/var
      - /var/lib/docker/containers:/host/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/docker/log:ro

**Comment by arctan5x** [comment]
We will expose s2s_port and svc_port as ENV vars and update the documentation.

**Comment by arctan5x** [comment]
PR has been made and will be merged after review.
