### ISSUE TITLE
Splunk 7.3.1 missing

### ISSUE THREAD

**Issue by LorenKeagle** [splunk/docker-splunk#237]
We've been running 7.3.1 for several weeks now, and the image has since disappeared from dockerhub, breaking our build process and forcing us to revert to 7.3.0.  I see that two days ago there was a checking to 'revert 7.3.1', but no explanation or bugs files against it (that I can see).

Was this intentional to remove an existing image without replacing it?  Was there some bug or security vulnerability that forced the decision?

**Comment by bb03** [comment]
@LorenKeagle This post might best answer your question.  Let me know if you have additional questions.

https://answers.splunk.com/answers/771315/where-did-splunk-731-go.html

**Comment by arctan5x** [comment]
We are in the process of releasing 7.3.1.1. Closing this ticket.
