### ISSUE TITLE
How to select free license for dev purposes?

### ISSUE THREAD

**Issue by yjo** [splunk/docker-splunk#251]
I'd like to configure docker-splunk to start up with the 'Free' license group on first start up. The use case is for developers running a dockerised version of our application infrastructure on their machines.

Is there a sensible way of doing this with the current implementation?  Once the container has started using the enterprise trial license I can add 
```
[license]
active_group = Free
```
to /opt/splunk/etc/system/local/server.conf, but this file isn't created before first run - am I missing a trick for setting configuration via environment variables or Dockerfile additions?

Thanks!

**Comment by nwang92** [comment]
Hmm this does seem to be a bit of a gap at the moment - currently not specifying `SPLUNK_LICENSE_URI` just gives you the trial license. Maybe we can add a special condition for `SPLUNK_LICENSE_URI=Free`?

**Comment by nwang92** [comment]
For a workaround, you could do any of the following:
- Use a `default.yml` and specify the setting yourself in `server.conf` using the custom conf file: https://github.com/splunk/docker-splunk/blob/develop/docs/ADVANCED.md#create-custom-configs
- Use a custom playbook, mount/add it to your container, and wire it up with the `SPLUNK_ANSIBLE_POST_TASKS` env var
- Do it manually through the web UI/REST API

**Comment by yjo** [comment]
Thanks @nwang92.  I tried your first option, but that (or adding a `/opt/splunk/etc/system/local/server.conf` file in the Dockerfile) didn't seem to work - the changes were reverted by some process or other on first run of the container.  What did work for me was adding the config to `/opt/splunk-etc/system/local/server.conf`:
```
[license]
active_group = Free
```

But I agree that the ideal solution would be special handling of `SPLUNK_LICENSE_URI` or some other environment variable so that users don't need to customise the container further.

**Comment by nwang92** [comment]
I added support for `SPLUNK_LICENSE_URI=Free` as part of https://github.com/splunk/splunk-ansible/pull/281. This should be available in `splunk/splunk:edge` which gets built nightly, and it'll likely be available in the next release of Splunk images (at the time of this post, we're currently on 8.0.0).
