### ISSUE TITLE
Support for ARM

### ISSUE THREAD

**Issue by JamesRiley** [splunk/docker-splunk#254]
I am trying to install the Universal Forwarder on a RaspberryPi 3 device running Ubuntu-Core.
Therefore I can only use snaps or docker containers. 
There does not appear to be a docker container for Universal Forwarder for Linux/armv7l. Can one be created please?

TIA
James

**Comment by nwang92** [comment]
cc @mikedickey

**Comment by arctan5x** [comment]
Will update if Linux/armv7l universal forwarder is decided to be supported officially. Closing for now.
