### ISSUE TITLE
Can you provide an example yml file showing non-clustered indexers?

### ISSUE THREAD

**Issue by azilbersteinSFDC** [splunk/docker-splunk#257]
Hi,

I'd like to experiment with a Splunk cluster that contains: 3 searchheads in a cluster; 1 license master; 3 non-clustered indexers (without data replication). Can you provide an example of how to set it up? I went through the examples (in https://github.com/splunk/docker-splunk/tree/develop/test_scenarios) and couldn't find anything - the `SPLUNK_INDEXER_URL` parameter is used only with clustered indexers. Sorry if I missed it!

**Comment by nwang92** [comment]
That parameter is used for both clustered and non-clustered indexer tiers. You can refer to either https://github.com/splunk/docker-splunk/blob/develop/test_scenarios/1sh2idx2hf.yaml (minus the forwarders) or https://github.com/splunk/docker-splunk/blob/develop/test_scenarios/2idx2sh.yaml.

When `SPLUNK_CLUSTER_MASTER_URL` is supplied, the search heads will add the cluster master as a search peer. In the absence of this env var, if `SPLUNK_INDEXER_URL` is found it will peer the indexers directly. You may find scenarios with both of these env vars defined, which is more of a common/best practice we've found to explicitly outline the entire topology from any one container. In certain roles, some of the env vars won't necessarily be used though - for example, if you are using a cluster master, you can probably drop `SPLUNK_INDEXER_URL` entirely from the search head containers without impacting your deployment.

**Comment by azilbersteinSFDC** [comment]
Thank you @nwang92 . I think that in order to achieve my desired setup (3 independent indexers with no replication) all I need to do is to define `replication_factor: 1` in the `default.yml` file.

**Comment by nwang92** [comment]
That replication factor is actually only used for indexer clusters (through the cluster master) - by default, if you peer indexers directly to search heads, the indexers won't be sharing data between themselves because they have no central master. So they will naturally have a "replication" factor of 1. If an indexer goes down, you'd lose search access to any data that indexer would've held.

**Comment by azilbersteinSFDC** [comment]
I see @nwang92 . So it is the presence of the Cluster Master node that decides if the Indexers are clustered - if it's present then they form a cluster otherwise they're independent. And anyway you choose, you should still configure all your indexers to know about all of them (e.g. `SPLUNK_INDEXER_URL=idx1,idx2`). Did I get it right?

And a follow up question: does the Cluster Master have any other benefits - is it worthwhile to keep it around even if the indexers are not clustered?

**Comment by nwang92** [comment]
Yeah, that's correct. 

Outside of coordinating pools of indexers and handling indexer discovery when things go in and out of service, the cluster master can also be used to distribute apps/bundles of configs to your indexers. Say you have a fleet of 100 indexers that all require the same props + transforms to mold your data, it can be tedious to manually set them all up. If you instruct the cluster master to install that app/bundle, it will be responsible for distributing the configs to the various peers and making sure they are in sync. Technically if you forgo the cluster master, you can also just tell every `SPLUNK_ROLE=splunk_indexer` container to also download the app themselves via `SPLUNK_APPS_URL=<url>`, but then you may want to consider the network infrastructure of your environment (ex: 100 clients downloading a tarball from a single server, or 1 client downloading the tarball then distributing the tarball within the docker/k8s internal network). 

There's some other minor advantages such as the ability to trigger rolling restarts of your indexer pool, multi-site, etc. but it depends on how large of a Splunk deployment you have. Obviously Splunk Docs around this will go into all the features and you can decide if you want it or not :) 

https://docs.splunk.com/Documentation/Splunk/7.3.2/Indexer/Clusterdeploymentoverview

**Comment by azilbersteinSFDC** [comment]
Awesome. Thank you so much @nwang92 .
