### ISSUE TITLE
The container is painful to use

### ISSUE THREAD

**Issue by rlewkowicz** [splunk/docker-splunk#264]
So coming into this, I'm just looking for the inputs.conf. I expect it to be somewhere in the container already. There's no find. But there's also no apt, no yum, no apk. I can't trouble shoot or debug this thing, some of your TOC links don't work. 

I need to mount a path into the container, but I can't figure out where and I can't explore the container, because it's aggressively minimal

**Comment by rlewkowicz** [comment]
It also drops you into a shell as the ansible user which appears to not have permission to access most things

**Comment by bb03** [comment]
Hi Ryan.  Let me give you some more overview.  We have three users
* ansible - super-user, runs ansible plays for configuration
* splunk - owns the contents of /opt/splunk and has restricted access to other parts of the container
* root

We default to the ansible account, so to do the things in the /opt/splunk you'll need to sudo to the splunk user.  For the new container, we use microdnf as the package manager.

Hope this helps you get started.

**Comment by rlewkowicz** [comment]
I switched to fluentd and HEC. Thanks though!
