### ISSUE TITLE
How to deploy a cluster index splunk with docker compose on two server

### ISSUE THREAD

**Issue by nabiljsk** [splunk/docker-splunk#270]
Hello,
I want to deploy a clustering index splunk with docker compose with docker compose on two server.

In the first server (192.168.10.10), I have two splunk container (searchead and indexer), and in the secend server (192.168.20.10), Ihave three splunk conteniar (cluster master ,searchead and indexer) 
here are the files yml I used:

file server one

`# sever1.yml (192.168.10.10)

version: '2'
services:

 search-head-idmbs-in002-log:
    image: splunk/splunk:7.2.7
    hostname: search-head-idmbs-in002-log
    container_name: search-head-idmbs-in002-log
    command: start
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=***********
      - SPLUNK_UPGRADE=false
      - SPLUNK_INDEXER_URL=indexer-idmbs-in002-log,192.168.20.10:21089
      - SPLUNK_CLUSTER_MASTER_URL=192.168.20.10:20089
      - SPLUNK_ROLE=splunk_search_head
      - DEBUG=true
    ports:
      - "9443:8000"
      - "8089:8089"
    volumes:
      - /opt/container-data/splunk/config/global/authentication.conf:/opt/splunk/etc/system/local/authentication.conf
      - /opt/container-data/splunk/config/global/authorized.conf:/opt/splunk/etc/system/local/authorized.conf
      - /opt/container-data/splunk/config/global/props.conf:/opt/splunk/etc/system/local/props.conf
      - /opt/container-data/splunk/config/global/web.conf:/opt/splunk/etc/system/local/web.conf
      - /opt/container-data/splunk/config/apps:/tmp/apps
      - /opt/container-data/splunk-search-head/etc:/opt/splunk/etc
      - /opt/container-data/splunk-search-head/var:/opt/splunk/var    
	  
  indexer-idmbs-in002-log:
    image: splunk/splunk:7.2.7
    command: start
    hostname: indexer-idmbs-in002-log
    container_name: indexer-idmbs-in002-log
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=********
      - SPLUNK_SEARCH_HEAD_URL=search-head-idmbs-in002-log,192.168.20.10:8089
      - SPLUNK_INDEXER_URL=indexer-idmbs-in002-log,192.168.20.10:21089
      - SPLUNK_CLUSTER_MASTER_URL=192.168.20.10:20089
      - SPLUNK_IDXC_SECRET=jsknabil46
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_UPGRADE=false
      - DEBUG=true
    ports:
      - "21443:8000"
      - "21089:8089"
      - "21997:9997"
    volumes:
      - /opt/container-data/splunk-indexer/etc:/opt/splunk/etc
      - /opt/container-data/splunk-indexer/var:/opt/splunk/var
      - /data/hot/splunk:/data/hot/splunk
      - /data/cold/splunk:/data/cold/splunk
      - /data/frozen/splunk:/data/frozen/splunk
      - /data/thawed/splunk:/data/thawed/splunk  `

the file of the secend server: 

`# sever2.yml (192.168.20.10)

version: '2'
services:

  cluster-master-idmlu-in002-log:
    image: splunk/splunk:7.2.7
    hostname: cluster-master-idmlu-in002-log
    container_name: cluster-master-idmlu-in002-log
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=indexer-idmlu-in002-log,192.168.10.10:21089
      - SPLUNK_SEARCH_HEAD_URL= search-head-idmlu-in002-log,192.168.10.10:8089
      - SPLUNK_CLUSTER_MASTER_URL=cluster-master-idmlu-in002-log
      - SPLUNK_ROLE=splunk_cluster_master
      - SPLUNK_PASSWORD=********
      - SPLUNK_IDXC_SECRET=**********
      - DEBUG=true
    ports:
      - "20443:8000"
      - "20089:8089"
      - "9887:9887"
    volumes:
      - /opt/container-data/splunk_cluster-master/etc:/opt/splunk/etc
      - /opt/container-data/splunk_cluster-master/var:/opt/splunk/var
      - /opt/container-data/splunk/config/global/indexes.conf:/opt/splunk/etc/master-apps/_cluster/local/indexes.conf
      
   search-head-idmlu-in002-log:
    image: splunk/splunk:7.2.7
    hostname: search-head-idmlu-in002-log
    container_name: search-head-idmlu-in002-log
    command: start
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=************
      - SPLUNK_UPGRADE=false
      - SPLUNK_INDEXER_URL=indexer-idmlu-in002-log,192.168.10.10:21089
      - SPLUNK_CLUSTER_MASTER_URL=cluster-master-idmlu-in002-log
      - SPLUNK_ROLE=splunk_search_head
      - DEBUG=true
    ports:
      - "9443:8000"
      - "8089:8089"
    volumes:
      - /opt/container-data/splunk/config/global/authentication.conf:/opt/splunk/etc/system/local/authentication.conf
      - /opt/container-data/splunk/config/global/authorized.conf:/opt/splunk/etc/system/local/authorized.conf
      - /opt/container-data/splunk/config/global/props.conf:/opt/splunk/etc/system/local/props.conf
      - /opt/container-data/splunk/config/global/web.conf:/opt/splunk/etc/system/local/web.conf
      - /opt/container-data/splunk/config/apps:/tmp/apps
      - /opt/container-data/splunk-search-head/etc:/opt/splunk/etc
      - /opt/container-data/splunk-search-head/var:/opt/splunk/var    
	  
  indexer-idmlu-in002-log:
    image: splunk/splunk:7.2.7
    command: start
    hostname: indexer-idmlu-in002-log
    container_name: indexer-idmlu-in002-log
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=***********
      - SPLUNK_SEARCH_HEAD_URL=search-head-idmlu-in002-log,192.168.10.10:8089
      - SPLUNK_INDEXER_URL=indexer-idmlu-in002-log,192.168.10.10:21089
      - SPLUNK_CLUSTER_MASTER_URL=cluster-master-idmlu-in002-log
      - SPLUNK_IDXC_SECRET=************
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_UPGRADE=false
      - DEBUG=true
    ports:
      - "21443:8000"
      - "21089:8089"
      - "21997:9997"
    volumes:
      - /opt/container-data/splunk-indexer/etc:/opt/splunk/etc
      - /opt/container-data/splunk-indexer/var:/opt/splunk/var
      - /data/hot/splunk:/data/hot/splunk
      - /data/cold/splunk:/data/cold/splunk
      - /data/frozen/splunk:/data/frozen/splunk
      - /data/thawed/splunk:/data/thawed/splunk  `

after running the docker-compose command, i got this error in the cluster master

`Failed to add peer 'guid=DB000187-EAF3-4D7A-BA17-1FC909CC67D8 server name=indexer-idmbs-in002-log ip=192.168.10.10:8089' to the master. Error=error accessing uri=https://192.168.10.10:8089/services/cluster/config, statusCode=401, description=Unauthorized.`

can you help me , to solve the problem

thanks

Regards

**Comment by bb03** [comment]
@nabiljsk Can I ask a couple questions about your environment?  Are the passwords the same across all components?  If they are not, try again with identical passwords across the cluster.  If the problem still persists, I would ask you to log in through the UI on each component through the UI.  Ideally, each container should be up and reachable.  If they aren't, can you check the status of each container?  Sometimes the OOM killer will remove Splunk instances if docker has a low memory cap.  Also, I would appreciate seeing more of the error message/logs.

Thanks,
Brent

**Comment by nwang92** [comment]
To add on: I think the ideal solution would be to take your 2 servers and `docker swarm init` + `docker swarm join` them together to form a 2-node swarm cluster. Then, you can create only 1 compose file (ex: https://github.com/splunk/docker-splunk/blob/develop/test_scenarios/3idx3sh1cm.yaml) which share the same overlay network and you can reference containers internally in that deployment using container names, exposed ports, etc.

**Comment by nabiljsk** [comment]
Hello @bb03  

the password is the same in all instances, and the status of all contener i up.

I have these message in logs in indexer-idmbs-in002-log
`11-07-2019 10:17:04.095 +0000 WARN  CMSlave - Failed to register with cluster master reason: failed method=POST path=/services/cluster/master/peers/?output_mode=json master=192.168.20.10:20089 rv=0 gotConnectionError=0 gotUnexpectedStatusCode=1 actual_response_code=500 expected_response_code=2xx status_line="Internal Server Error" socket_error="No error" remote_error=Cannot add peer=192.168.10.10 mgmtport=8089 (reason: error accessing uri=https:// 192.168.10.10:8089/services/cluster/config, statusCode=401, description=Unauthorized). [ event=addPeer status=retrying AddPeerRequest: { _id= active_bundle_id=B779DB3DBF292E2713C5EE04B9588B37 add_type=Initial-Add base_generation_id=0 batch_serialno=1 batch_size=1 forwarderdata_rcv_port=9997 forwarderdata_use_ssl=0 last_complete_generation_id=0 latest_bundle_id=B779DB3DBF292E2713C5EE04B9588B37 mgmt_port=8089 name=DB000187-EAF3-4D7A-BA17-1FC909CC67D8 register_forwarder_address= register_replication_address= register_search_address= replication_port=9887 replication_use_ssl=0 replications= server_name=indexer-idmbs-in002-log  splunk_version=7.2.7 splunkd_build_number=f817a93effc2 status=Up } ].`

regards

**Comment by nabiljsk** [comment]
Hello @nwang92 
I have do the docker docker swarm init + docker swarm join and I have spécifiée the server one as manager;
But when I run docker stack deploy -c docker-compose.yml splunk , I have this error :  

`invalid mount config for type bind: bind mount source path does not exist: /opt/container-data/splunk/config/global/`

how can I solve this error ?

regards

**Comment by bb03** [comment]
@nabiljsk Whatever's going on, docker does not think that the /opt/container-data/splunk/config/global directory exists.  So I would suggest you check a couple things first.
1) Verify that the directory exists, that there are no misspellings in the path, etc.
2) Verify that the permissions are correct so the docker user has visibility into the folder.

**Comment by nabiljsk** [comment]
Hello @bb03 
How I can acces to the interface web of each service splunk?

regards

**Comment by bb03** [comment]
@nabiljsk if its up and running, ```docker ps``` should show you the port mappings associated with the container.  Look for what the container's port 8000 is mapped to.

**Comment by arctan5x** [comment]
@nabiljsk 

Closing this ticket due to the last update being a while ago. Let us know if the solution didn't work.
