### ISSUE TITLE
error docker launch splunk_build_type undefined

### ISSUE THREAD

**Issue by KlausGlueckert** [splunk/docker-splunk#271]
getting fatal: [localhost]: FAILED! => {} 'splunk_build_type' is undefined when I launch a docker

` docker run -it -p 8000:8000 -e "SPLUNK_PASSWORD=<password>" -e "SPLUNK_START_ARGS=--accept-license" splunk/splunk:latest`

my system is ubuntu 18

**Comment by KlausGlueckert** [comment]
also splunk/splunk:8.0.0 is throws the same error

**Comment by bb03** [comment]
@KlausGlueckert I'll start taking a look at this

**Comment by bb03** [comment]
I'm not able to reproduce the error, can you send me the SHA of the image you're working with?  Or just do a ```docker pull splunk/splunk:latest``` to make sure you're on the most current image

**Comment by KlausGlueckert** [comment]
@bb03 Yes, using sha256:8f5a586f4e63565399b1116562592b5bdd0b4e8b0183c045bf36fd154b99a367

I found out that this error only happens if I mount volumes like /opt/splunk. I just read that appearantly you should only mount /opt/splunk/var and /opt/splunk/etc.

Maybe it's useful to mention this on https://github.com/splunk/docker-splunk or include an example mounting just those 2 folders

    #-v /home/geoSplunk/admin:/opt/splunk/etc/users/admin \
    #-v /home/geoSplunk/root:/opt/splunk \

**Comment by henricook** [comment]
@KlausGlueckert This "only mounting etc and var" is really frustrating. I'm on a system where I can only attach one persistent volume and trying to work around it is pretty tough!

Do you know more on why this error happens and how I might be able to get around it with only one mount point?

**Comment by KlausGlueckert** [comment]
@henricook I believe it is designed that you have to mount var and etc, but maybe try to just mount the splunk root directory. It any case you MUST use predefined docker volumes, I didnt get it to work with just docker run, only with docker-compose. see here: https://splunk.github.io/docker-splunk/STORAGE_OPTIONS.html. If you need to update the image later, you set - SPLUNK_UPGRADE=true in the compose file. Hope that helps....

**Comment by henricook** [comment]
Thanks for the tip, pre-defined volumes gave me hope for a minute. I think you mean adding `VOLUME ["/opt/splunk"]` to the top of my Dockerfile (link to other ticket: https://github.com/splunk/docker-splunk/issues/408). It didn't make a different unfortunately, looking at the container /opt/splunk is still pretty empty when ansible fails with 'splunk_build_type' is undefined.

**Comment by KlausGlueckert** [comment]
...try first to get it to work with docker-compose and 2 volumes, if that works, try to change it to 1 volume. Not sure if it will work with a Dockerfile. I would try to build a docker-compose environment or docker stack deploy if you have distributed cluster setup

**Comment by lukeyeager** [comment]
NOTE: you can also get this error when you [mistakenly] try to use `SPLUNK_ROLE=splunk_universal_forwarder` with the `splunk/splunk` image instead of the `splunk/universalforwarder` image.
