### ISSUE TITLE
What happened to debian/why is redhat the new default?

### ISSUE THREAD

**Issue by defektive** [splunk/docker-splunk#275]
Previously we had to opt in to redhat by adding `-redhat` to a tag. Starting with version 8, it seems redhat is the default and there isn't a debian tag that I could find. Was this intentional? Will there be a debian tag?

**Comment by nwang92** [comment]
cc @mikedickey 

Yeah this was an intentional change for OpenShift compliance. I believe only 7.3.x series will be supporting both debian + redhat, but 8.x and beyond will likely support redhat for the foreseeable future.

**Comment by mikedickey** [comment]
Please see [this blog article](https://www.splunk.com/blog/2019/05/08/an-insider-s-guide-to-splunk-on-containers-and-kubernetes.html) for more info. I plan to publish a follow-up article about changes in 8.0 soon, but it has been delayed.
