### ISSUE TITLE
7.3.1-7.3.2 JAVA issue

### ISSUE THREAD

**Issue by PaleWooten** [splunk/docker-splunk#290]
Hi!
I ve got a problem with starting a docker container with 7.3.2 image. When im adding java - its just dont work.

```
TASK [splunk_common : Get the openjdk apt key] *********************************
fatal: [localhost]: FAILED! => {
"changed": true,
"cmd": "set -o pipefail\nwget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -\n",
"delta": "0:45:43.028626",
"end": "2019-12-03 13:52:15.139190",
"rc": 2,
"start": "2019-12-03 13:06:32.110564"
}

STDERR:

Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.

MSG:

non-zero return code
```

**Comment by PaleWooten** [comment]
im using proxy and docker-compose:


 ```
 splunk1:
     networks:
       splunk_net:
         aliases:
           - splunk1.sovcombank.group
     image: splunk/splunk:7.3.1
#     image: splunk/splunk:7.3.2
     command: start
     hostname: splunk1.sovcombank.group
     container_name: splunk1
     environment:
       - SPLUNK_START_ARGS="--accept-license"
       - SPLUNK_LICENSE_URI
       - DEBUG=true
       - http_proxy=http://uhq-proxy1:3128
       - https_proxy=http://uhq-proxy1:3128
       - no_proxy=
       - JAVA_VERSION=openjdk:8
     ports:
       - "8089:8089"
     volumes:
       - /mnt/sas/data/splunk1-etc:/opt/splunk/etc
#       - /mnt/sas/data/splunk1-bin-scripts/upload_perimeter.sh:/opt/splunk/bin/scripts/upload_perimeter.sh
       - /mnt/sas/data/splunk1-var:/opt/splunk/var
       - /mnt/sas/compose/prod-bak/splunk/defaults:/tmp/defaults
       - /mnt/sas/compose/prod-bak/splunk/proxy.conf:/etc/apt/apt.conf.d/proxy.conf
       - "/etc/localtime:/etc/localtime:ro"
       - /mnt/sas/data/splunk1-share:/opt/splunk/share/splunk/search_mrsparkle/exposed/fonts
```

**Comment by PaleWooten** [comment]
After that ive tried to start 8.0 - all works fine. But i need exactly 7.3.2

**Comment by bb03** [comment]
@PaleWooten Okay, thank you for letting us know. We'll start tracking this internally and look at updating the 7.3.2 container with the latest splunk-ansible. Ping me again if I don't add an ETA by Thursday.

**Comment by bb03** [comment]
@PaleWooten would a 7.3.2.1 build be suitable for your needs?

**Comment by PaleWooten** [comment]
Yeah,i just cant get to 8.0 yet because of python scripts that i have.

I just need some stable 7.3* with java. Strange thing - i have some old 7.3.1 edge build with no java problems

**Comment by PaleWooten** [comment]
Just now tested 7.3.3 - same error

**Comment by hendolim** [comment]
Taking a look at it. By any chance, were you on different networks when trying to start these containers @PaleWooten ? The reason Im asking is that sometimes some of these key/license server block requests if you are behind proxy, on corporate network, and things like that.

**Comment by hendolim** [comment]
I tried on my local and it works with all the 7.3.* images.
Also, on the current 8.0.0 image we do not support Java, so the container will start successfully but no Java will be installed.
So yeah, let me know if your network varies between all those run.

**Comment by PaleWooten** [comment]
All those runs are made on one machine with same settings. im using our corporate nginx proxy - as you can see in compose file. 
  - http_proxy=http://uhq-proxy1:3128
  - https_proxy=http://uhq-proxy1:3128

As for apt-get -       - /mnt/sas/compose/prod-bak/splunk/proxy.conf:/etc/apt/apt.conf.d/proxy.conf
im mapping proxy within a file

i know that it might be  a proxy,but i cant work without it

**Comment by hendolim** [comment]
@PaleWooten Using the proxy, were you able to run any 7.3.* container succesfully with Java installed at all?
I will look into other sources where we are able to get the OpenPGP key through proxy.

**Comment by PaleWooten** [comment]
I've got some old edge image:
```
Splunk Enterprise
Version:
7.3.1
Build:
bd63e13aa157
```

It works fine on exact same settings. With openjdk and proxy

**Comment by PaleWooten** [comment]
Ive tested latest edge image (18353691fd2e linux/amd64) right now - error too,but different 
```
TASK [splunk_common : Install openjdk for Redhat] ******************************
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": [
        "microdnf",
        "install",
        "java-1.8.0-openjdk"
    ],
    "delta": "0:00:31.292050",
    "end": "2019-12-09 15:01:21.445400",
    "rc": 1,
    "start": "2019-12-09 15:00:50.153350"
}

STDOUT:

Downloading metadata...


STDERR:


(process:223): librhsm-WARNING **: 15:00:51.241: Found 0 entitlement certificates

(process:223): librhsm-WARNING **: 15:00:51.243: Found 0 entitlement certificates
error: cannot update repo 'ubi-8-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (28): Timeout was reached for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/baseos/os/repodata/repomd.xml [Connection timed out after 30001 milliseconds]


MSG:

non-zero return code
```

**Comment by hendolim** [comment]
@PaleWooten on the old 7.3.1 edge you have can you run `cat /etc/*-release` and paste the output here

**Comment by PaleWooten** [comment]
Here it is

```
ansible@splunk1:/opt/splunk$ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by PaleWooten** [comment]
And java version 
```
ansible@splunk1:/opt/splunk$ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-1~deb9u1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```

**Comment by hendolim** [comment]
I see, the latest 7.3.* images are all Debian 10. On Debian 9 we use different Java installation that does not involve fetching the PGP key from the license/key server.
I will look into PGP key source that can work with proxy.
But in the mean time, to unblock yourself you can build a Debian 9 container from this repo and use that.

**Comment by PaleWooten** [comment]
You have some instructions how to build that? 

And another question - in redhat as i can see i have a problem with proxy,env variablse seems either not working,or nor affecticting java installer. 
Can you tell me how to set up proxy correct in redhat image?

**Comment by hendolim** [comment]
Checkout the version you'd like:
`git checkout 7.3.2`
then build:
`make splunk-debian-9`
the image will be tagged as 'splunk-debian-9:latest'

**Comment by hendolim** [comment]
In the current released version of redhat container, the splunk-ansible is not updated to support Java. If you need a redhat container that support Java, you can pull splunk-ansible from `develop` branch, put it inside your docker-splunk repo and build the image: `make splunk-redhat-8`

**Comment by PaleWooten** [comment]
Ive tried to fork and clone repo - but it didnt work,even after i set up proxy for git 

```
 git clone git@github.com:PaleWooten/docker-splunk.git
Cloning into 'docker-splunk'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

```

**Comment by PaleWooten** [comment]
Another question - is image 8.0.1 supports java? 
As i can see - it redhat

**Comment by PaleWooten** [comment]
@hendolim ,i've tried to make image - but still got issue with gpg

```
Current default time zone: 'Etc/UTC'
Local time is now:      Thu Dec 19 13:35:36 UTC 2019.
Universal Time is now:  Thu Dec 19 13:35:36 UTC 2019.

Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.jiQ61kCx4I/gpg.1.sh --keyserver https://keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
gpg: keyserver receive failed: Connection timed out
The command '/bin/sh -c /install.sh && rm -rf /install.sh' returned a non-zero code: 2
make: *** [base-debian-9] Error 2
```

**Comment by arctan5x** [comment]
8.0.1 supports Java. Please keep gpg issue separately from this thread. Closing this issue and feel free to reopen if you see a persisting Java issue.
