### ISSUE TITLE
Splunk fails to start after changing admin password

### ISSUE THREAD

**Issue by romanmelko** [splunk/docker-splunk#298]
Hello,

When changing admin password after the installation Splunk fails to start. I suppose this is due to ansible's implementation inside the container which uses $SPLUNK_PASSWORD environment variable originally set during **docker run** command. 
The password change mechanism does not updates that variable so ansible playbook fails to perform some actions via REST API during start:

```
TASK [splunk_common : Test basic https endpoint] *******************************
fatal: [localhost]: FAILED! => {
    "cache_control": "private", 
    "changed": false, 
    "connection": "Close", 
    "content": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<response>\n  <messages>\n    <msg type=\"ERROR\">Unauthorized</msg>\n  </messages>\n</response>\n", 
    "content_length": "130", 
    "content_type": "text/xml; charset=UTF-8", 
    "date": "Thu, 02 Jan 2020 16:01:01 GMT", 
    "elapsed": 0, 
    "redirected": false, 
    "server": "Splunkd", 
    "status": 401, 
    "url": "https://127.0.0.1:8089/services/properties", 
    "vary": "Cookie, Authorization", 
    "www_authenticate": "Basic realm=\"/splunk\"", 
    "x_content_type_options": "nosniff", 
    "x_frame_options": "SAMEORIGIN"
}

MSG:

Status code was 401 and not [200, 404]: HTTP Error 401: Unauthorized
```
Version: 8.0.1; also reproducible on previous versions.

So my question is the following - is it OK? What is the proper way of changing admin password?

Thanks

**Comment by arctan5x** [comment]
Hello, how are you changing the admin password? We support changing the password during the initial container start time through changing the container env variable. You can either pass in the variable through the docker run command or a yaml file (if you use docker-compose).

**Comment by romanmelko** [comment]
Hi @arctan5x,

Yes, this is known about setting initial password during the deployment. 
I was talking about changing the password later (via Splunk Web or REST API) when such a need occurs. When we change it later via UI then after restart Splunk can't start due to not updated environment variable. 

So my question is - does this approach means that we have to re-deploy the container every time when we decide to change the password?

Thanks

**Comment by arctan5x** [comment]
@romanmelko 

I changed my Splunk password via UI, restarted Splunk, and was able to re-login with the changed password. Splunk itself doesn't check the environment variable when it starts. So as long as your container is alive (without restarting a container), your Splunk should work with any changed passwords.

We have a logic baked into a container that checks the environment variable (separate from Splunk software) to set the initial password. Therefore, if you re-deploy (or restart) the container, this logic will check the env var again. There is also a way to bypass this by turning off this logic at the container start time. Please check the documentation for that.

**Comment by romanmelko** [comment]
Hi @arctan5x 
That's exactly what I was talking about. Sorry for not being clear on that. 
My issue is applicable when container restarts after changing the password through the GUI, REST API or CLI. Unfortunately I haven't found how to bypass this logic in documentation. Anyway, now I know that this is known behavior. 
I think we may now close this issue.

Thank you

**Comment by nwang92** [comment]
If you change the admin password after a successful container creation using these images, you'll need to either:
* Update the `SPLUNK_PASSWORD` environment variable you started the container ith
* Update the `default.yml` file that is volume-mounted to the container (either via configMap or secret, if using k8s) and make the new password reflected in `splunk.password`

But at the moment, there's not a better of way handling Splunk admin password rotations - there needs to be some intervention by an operator or an automated procedure to update the container definition that the original password has been changed.
