### ISSUE TITLE
Document SPLUNK_APPS_URL param

### ISSUE THREAD

**Issue by aegershman** [splunk/docker-splunk#30]
[The documentation does not appear to make mention of the `SPLUNK_APPS_URL` parameter](https://github.com/splunk/docker-splunk/blob/master/splunk/debian-9/entrypoint.sh#L120)-- and, unfortunately, when I tested it, it did not appear to properly install any of the splunkbase app urls I supplied.

Is this intentional?

Thank you for your time

## background

I have a usecase for spinning up ephemeral Splunk Heavy Forwarders inside k8 pods; their only job being to forward [RFC5424 syslogs](https://splunkbase.splunk.com/app/978/) on to a corporate Splunk receiver. It would be incredibly, joyously convenient & clean for me to use this Docker image (rather than the docker-legacy 7.0.3-monitoring image) in the k8 deployment, and simply use the `SPLUNK_APPS_URL` param to install the RFC5424 syslog formatting add-on on the heavy forwarder.

**Comment by lephino** [comment]
This has portions of an upcoming feature, and in the current version on github does not function.  Please watch this following: 
https://github.com/splunk/docker-splunk/issues/14

Once this is resolved this functionality will fully be supported.

**Comment by nwang92** [comment]
@aegershman as an aside question, is your expectation to pass in a Splunkbase URL (ex: https://splunkbase.splunk.com/app/978/) to get the app? Or are you hosting the tarball internally somewhere such that the URL you provided is a direct link to the package (ex: http://example.com/rfc5424-syslog_11.tgz)?

**Comment by aegershman** [comment]
@lephino awesome, thank you 👍 

@nwang92 For my current use-case everything I need is available on Splunkbase, so passing as a Splunkbase URL is fine. But now that you're pointing it out, I can definitely see the value in passing an arbitrary link to a tarball. This would make it much easier for Splunk admin operators to onboard teams' custom add-ons, and generally make things more self-service for teams.
