### ISSUE TITLE
Splunk web user prefs for TZ is not working when running Splunk in a docker container

### ISSUE THREAD

**Issue by jgonzalez98555** [splunk/docker-splunk#301]
Hello! I have an issue with the TZ setting when changing it from the GUI, every time the TZ is changed to see the timestamp provided by the browser is updated as the format I want it gets not, I have tried to change it from the configuration files doing it manually going to /etc/users/username/local/user_prefs.conf, after restating the Splunk service I get the same behavior, this has been detected on versions 7.3.3 and 8.0.1.

Has anybody run into the same issue before? I am not very familiar with docker so any help will be kindly accepted.

Thanks so much,

**Comment by nwang92** [comment]
Let me give this a whirl - can you provide the steps you took when you changed the timezone from SplunkWeb just to make sure I'm not missing anything?

**Comment by nwang92** [comment]
I think I'm able to reproduce what you're seeing - it seems like with 8.0.1 changing the user's timezone preference does not reflect in updated timestamps when executing a new search (ex: `index=_internal`) 

Doing this on 8.0.0 or other versions will show the updated timestamps when re-executing searches. This seems more of a problem in the Splunk product itself and it seems unlikely docker itself has anything to do with it. But let me see if this is being tracked internally.

**Comment by nwang92** [comment]
K, I think it is indeed an issue with images where the server hosting Splunk was missing some tzdata packages to interpret timezones. This was available in previous debian packages, but I guess we never noticed this for redhat.
