### ISSUE TITLE
8.0.1 microdnf issue with proxy

### ISSUE THREAD

**Issue by PaleWooten** [splunk/docker-splunk#303]
Hi! After downloading new 8.0.1 image ive encountered some problems with microdnf:

`[ansible@splunk1 splunk]$ sudo microdnf install java-1.8.0-openjdk

(process:9931): librhsm-WARNING **: 16:01:38.293: Found 0 entitlement certificates

(process:9931): librhsm-WARNING **: 16:01:38.295: Found 0 entitlement certificates
Downloading metadata...
error: cannot update repo 'ubi-8-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (28): Timeout was reached for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/baseos/os/repodata/repomd.xml [Connection timed out after 30001 milliseconds]
[ansible@splunk1 splunk]$  microdnf install java-1.8.0-openjdk
error: failed to obtain lock 'metadata': Failed to create file “/var/cache/yum/lock/dnf-metadata.lock.RBR7D0”: Permission denied
`

As i can see - it didnt use my proxy,but ive set EV in docker file, and echo is showing them just fine

`[ansible@splunk1 splunk]$sudo echo $http_proxy
http://myproxy:3128
[ansible@splunk1 splunk]$ sudo echo $https_proxy
http://myproxy:3128
`

What can i do to make things work?

**Comment by hendolim** [comment]
Hi @PaleWooten 
Does this happen consistently? And did you run any other command before doing microdnf install?
If you did, can you try installing from a fresh state (before running anything) and see if it works

**Comment by hendolim** [comment]
And actually I can't tell if it is honoring your proxy env or not.
You can try with and without the proxy env and see if it emits the same error. It might actually be going through your proxy but some config in the proxy is causing timeout.

**Comment by PaleWooten** [comment]
Nope,its fresh install. 

Ive tried both - install after i start the clean image,and install it by adding JAVA_VERSION variable in docker file. 

In second case error is the same:

`TASK [splunk_common : Install openjdk for Redhat] ******************************
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": [
        "microdnf",
        "install",
        "java-1.8.0-openjdk"
    ],
    "delta": "0:00:31.329008",
    "end": "2019-12-31 00:25:08.512032",
    "rc": 1,
    "start": "2019-12-31 00:24:37.183024"
}

STDOUT:

Downloading metadata...


STDERR:


(process:220): librhsm-WARNING **: 00:24:38.258: Found 0 entitlement certificates

(process:220): librhsm-WARNING **: 00:24:38.261: Found 0 entitlement certificates
error: cannot update repo 'ubi-8-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (28): Timeout was reached for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/baseos/os/repodata/repomd.xml [Connection timed out after 30002 milliseconds]


MSG:

non-zero return code
`
And its still the same - even when i deleted proxy variables.

**Comment by PaleWooten** [comment]
Also i ve checked access rights on proxy - *.redhat.com is in whitelist

**Comment by PaleWooten** [comment]
curl is working fine:
[ansible@splunk1 splunk]$ curl https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has `moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>

**Comment by PaleWooten** [comment]
ok,i ve found workaround - but its pretty bad:
1) Start clean container
2) exec in it ,login as root(not ansible) 
3) export https_proxy=ip:port

Why proxy settings in docker file dosent affect root user?

**Comment by bb03** [comment]
Took a quick look at our sudoers, and we have ```env_reset``` enabled. My guess is that this is getting picked up by ansible when we run ```sudo microdnf ``` .  After some poking around, this is probably the best option
https://docs.ansible.com/ansible/latest/user_guide/playbooks_environment.html

**Comment by PaleWooten** [comment]
Another issue with java - as i can see in ansible java task, JAVA_HOME only set when distrib is debian,and not when redhat is used. 

And as another workaround:
1) create file "environment"
`https_proxy=ip:port`
`http_proxy=ip:port`
`no_proxy=whatever`


2)map it in container 

`Volumes:`
 `- hostdirectory/environment:/etc/environment`

**Comment by PaleWooten** [comment]
Will some adjusments will be done to images? Doing and remebering all of this workarounds not so much of docker concepts(

**Comment by nwang92** [comment]
Sorry this ticket is a bit old, but since this ticket was created we did expose a `ansible_environment` key in the `default.yml` which adds environment variables to the Ansible runtime context. See: https://github.com/splunk/splunk-ansible/blob/develop/docs/advanced/default.yml.spec.md and https://github.com/splunk/splunk-ansible/pull/374

This can also be manipulated via the container env var `SPLUNK_ANSIBLE_ENV`. I wonder if it's possible to use this to set the http_proxy? For instance, something like:
```
docker run -d -P -e SPLUNK_ANSIBLE_ENV=http_proxy=http://proxy.local,https_proxy=https://proxy.local ...
```

**Comment by nwang92** [comment]
Going to close this because it's a bit stale, but if you find any future issues with this please feel free to comment or re-open this issue!

**Comment by friendlypenguin** [comment]
I had this issue (not related to splunk!) while using a RHEL8.6 Server that wasn't registered and had no subscription attached to it. It seems, that the entitlement certificates get mounted into the container, and when they are not present, some repos/content cannot be accessed.
Error msg was:
```
(microdnf:112): librhsm-WARNING **: 14:39:21.677: Found 0 entitlement certificates
error: No package matches 'libssh-devel'
```
