### ISSUE TITLE
JAVA_VERSION flag is not working after container recreating

### ISSUE THREAD

**Issue by PaleWooten** [splunk/docker-splunk#304]
Hi! Ive encoutered issuses with JAVA_VERSION flag. It dont work when container is recreated, if i have splunk\etc mapped from the host.

For understanding,here is my docker-compose file:

  `splunk1:`
     `networks:`
       `splunk_net:`
         `aliases:`
           - `splunk1.sovcombank.group`
     `image:` `splunk/splunk:8.0.1`
     `command:` `start`
     `hostname:` `splunk1.sovcombank.group`
     `container_name:` `splunk1`
     `environment:`
       `-` `SPLUNK_START_ARGS="--accept-license"`
       `-` `SPLUNK_LICENSE_URI`
       `-` `DEBUG=true`
       `-` `http_proxy=`
       `-` `https_proxy=`
       `-` `no_proxy=`
       `-` `JAVA_VERSION=openjdk:8`
     `ports:`
       `-` `"8089:8089"`
       `-` `"8000:8000"`
     `volumes:`
       `-` `/mnt/sas/data/splunk1-etc:/opt/splunk/etc`
       `-` `/mnt/sas/data/splunk1-var:/opt/splunk/var`
       `-` `/mnt/sas/compose/prod-bak/splunk/defaults:/tmp/defaults`
`#`       `-` `/mnt/sas/compose/prod-bak/splunk/proxy.conf:/etc/apt/apt.conf.d/proxy.conf`
`#`       `-` `/mnt/sas/compose/prod-bak/splunk/.bash_profile:/root/.bash_profile`
       `-` `/mnt/sas/compose/prod-bak/splunk/environment:/etc/environment`
       `-` `"/etc/localtime:/etc/localtime:ro"`

When it starts first - all fine,JAVA installing and all works. But when i change something in docker file after that and recreate container - ansible java task just not working,and i need to rm container and mapped volumes to clean start. 

Its reeeeally bad for automatic starts and etc. I need to copy etc and var by hand.

**Comment by nwang92** [comment]
Looks like I missed this issue - this should be fixed here: https://github.com/splunk/splunk-ansible/pull/338

We'll get it pushed out in the next Splunk image release (8.0.2).

**Comment by nwang92** [comment]
Also added a test for this here: https://github.com/splunk/docker-splunk/pull/309
