### ISSUE TITLE
could not set db path to provided in the env variable

### ISSUE THREAD

**Issue by kunalverma94** [splunk/docker-splunk#312]
transport endpoint is not connected. when i map config file.

 docker run -it  -p 8000:8000 -p 8088:8088    -e 'SPLUNK_START_ARGS=--accept-license' -e 'SPLUNK_PASSWORD=testpass'    -v ${pwd}:/app -e "SPLUNK_DB=/app" splunk/splunk
Error:
**fatal: [localhost]: FAILED! => {
    "changed": false, 
    "path": "/app/etc/.ui_login"
}**

 docker run -it  -p 8000:8000 -p 8088:8088    -e 'SPLUNK_START_ARGS=--accept-license' -e 'SPLUNK_PASSWORD=testpass'    -v ${pwd}:/app -e "SPLUNK_DB=/app"  -v ${pwd}:"/opt/splunk/var/lib/splunk" splunk/splunk

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "cmd": [
        "/opt/splunk/bin/splunk", 
        "start", 
        "--accept-license", 
        "--answer-yes", 
        "--no-prompt"
    ], 
    "delta": "0:00:02.345564", 
    "end": "2020-02-07 12:02:57.917002", 
    "rc": 10, 
    "start": "2020-02-07 12:02:55.571438"
}

STDOUT:

Splunk> All batbelt. No tights.

Checking prerequisites...
        Checking http port [8000]: open
        Checking mgmt port [8089]: open
        Checking appserver port [127.0.0.1:8065]: open
        Checking kvstore port [8191]: open
        Checking configuration... Done.
New certs have been generated in '/opt/splunk/etc/auth'.
        Checking critical directories...        Done
        Checking indexes...
                Creating: /opt/splunk/var/run/splunk/appserver/i18n
                Creating: /opt/splunk/var/run/splunk/appserver/modules/static/css
                Creating: /opt/splunk/var/run/splunk/upload
                Creating: /opt/splunk/var/run/splunk/search_telemetry
                Creating: /opt/splunk/var/spool/splunk
                Creating: /opt/splunk/var/spool/dirmoncache
                Creating: /opt/splunk/var/lib/splunk/authDb
                Creating: /opt/splunk/var/lib/splunk/hashDb

STDERR:

homePath='/opt/splunk/var/lib/splunk/audit/db' of index=_audit on unusable filesystem.
Validating databases (splunkd validatedb) failed with code '1'.  If you cannot resolve the issue(s) above after consulting documentation, please file a case online at http://www.splunk.com/page/submit_issue

MSG:

non-zero return code
Error splunkd.pid file is unreadable.

After tones of retry when i got it working it  could not set db path to provided in the env variable ..data is not populated in the  mounter folder

**Comment by nwang92** [comment]
Hmm from what I'm reading it seems like it is recommended you set `SPLUNK_DB` within `/opt/splunk/etc/splunk-launch.conf` which should be possible with the latest 8.0.2 version of the image:
```
docker run -d -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=helloworld -e SPLUNK_LAUNCH_CONF=SPLUNK_DB=/app -P splunk/splunk:8.0.2
```

Could you try that out with your use case and see if it works? Theoretically, you wouldn't be getting the stdout/stderr messages you see because SPLUNK_DB will no longer be the default `/opt/splunk/var/lib`
