### ISSUE TITLE
Instances are not able to monitor the full cluster

### ISSUE THREAD

**Issue by kurktchiev** [splunk/docker-splunk#313]
So this could 100% be user error, but I am trying to use the monitoring console to see the health of a test cluster I have deployed (3idxc3shc1cm1lm1dep-pvc). When I log into the Captain I am not able to see stats for the other search heads, and when I log into the Master i am unable to see any stats for the other indexers. In order to get stats I have to log into each individual instance to get its statistics, which is not as useful when I am testing performance and such. Thoughts/suggestions on what I am doing/expecting wrong?

**Comment by nwang92** [comment]
We have some work in our backlog to get [distributed monitoring console](https://docs.splunk.com/Documentation/Splunk/latest/DMC/DMCoverview) integrated with the rest of the docker-splunk project. Hoping to get it in the next release, so stay tuned!

**Comment by nwang92** [comment]
DMC is now included as part of https://github.com/splunk/splunk-ansible/pull/501. This new splunk_monitor role acts as a standalone search head over all instances in a deployment, and it automatically enables DMC in distributed mode with the peers/groups set appropriately.

cc @TheCamNelson, maybe it would be good to add an new README doc detailing how to use the DMC and the new `splunk_monitor` role in this repo? I'm thinking a new file in https://github.com/splunk/docker-splunk/tree/develop/docs/advanced with a link to it in https://github.com/splunk/docker-splunk/blob/develop/docs/ADVANCED.md
