### ISSUE TITLE
Formatting problem in documentation

### ISSUE THREAD

**Issue by CyrilleFranchet** [splunk/docker-splunk#314]
Hi, the line number 211 on page [https://splunk.github.io/docker-splunk/EXAMPLES.html] is erroneously escaped and it breaks all the formatting in client browser.

**Comment by alishamayor** [comment]
Yeah, GitHub Pages has some idiosyncrasies with how things like fenced code blocks and HTML elements are rendered, as compared to the Markdown on GitHub.com. We're currently working on a documentation update that will also include formatting changes to render the docs correctly for both. 

In the meantime, please reference the local [EXAMPLES.md](https://github.com/splunk/docker-splunk/blob/master/docs/EXAMPLES.md) file.
