### ISSUE TITLE
UF Container Splunk User UID/GID not 41812

### ISSUE THREAD

**Issue by drum7** [splunk/docker-splunk#319]
UF Container Splunk User UID/GID not 41812 for version 8.0.2 of container.  Docker user is 999:999 and ansible is 998:998.

Conflicts with documentation docs/SECURITY.md

**Comment by nwang92** [comment]
Good catch - I'm seeing the same thing. Let me dig into the Dockerfiles/build to see how this happened. It seems like `splunk/splunk:8.0.2` is unaffected.

**Comment by nwang92** [comment]
I'm closing this - I'll discuss internally with some folks to see if we want to republish the UF container images for this or if we'll just punt it to the next release.
