### ISSUE TITLE
DOC: Which volumes do I need to mount in order to persist my config, apps, and data?

### ISSUE THREAD

**Issue by westurner** [splunk/docker-splunk#339]
I've reviewed the listed resources, but I'm not sure which volumes I need to [bind] mount in my `docker run` command invocation or `docker-compose.yml` in order to persist my config, apps, and data?

- https://hub.docker.com/r/splunk/splunk
- https://github.com/splunk/docker-splunk/blob/develop/README.md
- https://docs.splunk.com/Documentation/Splunk/latest/Installation/Beforeyouinstall#Deploy_and_run_Splunk_Enterprise_inside_Docker_containers
  - https://docs.splunk.com/Documentation/Splunk/8.0.2/Installation/DeployandrunSplunkEnterpriseinsideDockercontainers
    - should this link to /latest/?
- https://docs.splunk.com/Documentation/Splunk/latest/Installation/Systemrequirements#Containerized_computing_platforms

**Comment by westurner** [comment]
I'm a home user who may be considering enterprise use.
I'm comparing Splunk with RRD, Prometheus, Grafana (which supports alerting for free), Loki, https://github.com/influxdata/sandbox (which supports alerting for free, can run on a RaspberryPi (ARM))

**Comment by nwang92** [comment]
There are docs around persistent volume usage: https://github.com/splunk/docker-splunk/blob/develop/docs/STORAGE_OPTIONS.md

But TLDR: `/opt/splunk/etc` will preserve any configurations you make (new viz, indexes, savedsearches, etc.) whereas `/opt/splunk/var` will preserve the indexed data.

We have in the midst of the process of making docs easier to read and navigate, sorry for the inconvenience!

**Comment by westurner** [comment]
Thanks! Should've looked in ``/docs``.

- [ ] A reference in ``/README.md`` would be helpful.
- [ ] A reference in https://docs.splunk.com/Documentation/Splunk/latest/Installation/DeployandrunSplunkEnterpriseinsideDockercontainers

Here's an (untested) example docker config that may be appropriate for the README:

```bash
SPLUNK_PASSWORD="<password>"
docker run \
  --name splunk \
  -p 8000:8000 \    # splunk web and HTTP interface
  -p 10514:10514 \  # syslog (optional)
  -e "SPLUNK_PASSWORD=${SPLUNK_PASSWORD}" \
  -e "SPLUNK_START_ARGS=--accept-license" \
  -v "$(PWD)"/etc:/opt/splunk/etc \
  -v "$(PWD)"/var:/opt/splunk/var \
  splunk/splunk:latest

# Review logs
docker logs splunk
docker logs -f splunk

# Run a shell as the 'ansible' user
docker exec -it splunk /bin/bash
# Run a shell as the 'splunk' user
docker exec -it splunk sudo -u splunk /bin/bash
docker exec -it splunk sudo -u splunk -i

# Enable syslog on udp and tcp
docker exec splunk \
  sudo -u splunk /opt/splunk/bin/splunk add udp 10514 \
    -sourcetype syslog -resolvehost true \
    -auth "admin:${SPLUNK_PASSWORD}"
docker exec splunk \
  sudo -u splunk /opt/splunk/bin/splunk add tcp 10514 \
    -sourcetype syslog -resolvehost true \
    -auth "admin:${SPLUNK_PASSWORD}"

# TODO: do these need indexes and add'l config?
docker exec -it splunk \
  sudo -u splunk /opt/splunk/bin/splunk \
    http-event-collector create collectd \
      -uri https://localhost:8089 \
      -description "collectd" \
      -sourcetype collectd_http

docker exec -it splunk \
  sudo -u splunk /opt/splunk/bin/splunk \
    http-event-collector create statsd \
      -uri https://localhost:8089 \
      -description "statsd" \
      -sourcetype statsd


# TODO: Install a splunk app
mkdir -p var/apps
(cd var/apps; wget "app.tgz")
docker exec splunk \
  sudo -u splunk /opt/splunk/bin/splunk install /opt/splunk/var/apps/app.tar
    # -auth "admin:${SPLUNK_PASSWORD}"

```

- https://docs.splunk.com/Documentation/Splunk/latest/Admin/CLIadmincommands
- https://docs.splunk.com/Documentation/Splunk/latest/Data/Monitornetworkports
  - https://wiki.splunk.com/Community:BestPracticeForConfiguringSyslogInput
  - Port 514 would require root, so e.g. 10514
- https://docs.splunk.com/Documentation/Splunk/latest/Data/UseHECfromtheCLI
  - https://docs.splunk.com/Documentation/Splunk/latest/Metrics/GetMetricsInCollectd
  - https://docs.splunk.com/Documentation/Splunk/latest/Metrics/GetMetricsInStatsd
- https://splunkbase.splunk.com/ (Splunk apps)
  - https://splunkbase.splunk.com/app/2890/ (Splunk Machine Learning Toolkit)
    - https://splunkbase.splunk.com/app/2882 (Python for Scientific Computing (for Linux 64-bit)

**Comment by nwang92** [comment]
Noted, that's a good suggestion. The top-level `README.md` of the repo has a link to the [published Github docs](https://splunk.github.io/docker-splunk/) but admittedly the link isn't very obvious and the workflow is still a little clunky.

Also just to note for your last example - [you can install apps at runtime](https://github.com/splunk/docker-splunk/blob/develop/docs/advanced/APP_INSTALL.md). Don't know your exact use-case, but you most likely don't need to save the app to `/opt/splunk/var/`. Apps are just tarballs and once the app is installed, a new directory will get created for that app in `/opt/splunk/etc/apps/<app-name>`. So assuming you have `/opt/splunk/etc/` backed up, it's a bit redundant to keep the untarred app + the tarred app on 2 different persistent storage layers.

I can get your examples added though, thanks for the help!

**Comment by westurner** [comment]
Thanks! Is there a good way to keep these app packages updated?
Python wheels with pinned versions, checksums, and TUF?
Or a different dependency tool like conda (and the conda-forge CI build and
upstream version watcher PR bot)? (Which would make managing
https://splunkbase.splunk.com/app/2882 Python for Scientific Computing and
anything in any language much easier, checksummed, and likely to be kept up
to date)

**Comment by nwang92** [comment]
From Splunkbase, I'm not too sure. Per the example in the docs, it is possible to add a version in the Splunkbase URL as follows:
```
environment:
    - SPLUNK_APPS_URL=https://splunkbase.splunk.com/app/2890/release/4.1.0/download
    ...
```

I'm guessing for that sci-py Splunk app, you can retrieve v1.4 via something like `https://splunkbase.splunk.com/app/2882/1.4/download` but v2.0.0 would be something like `https://splunkbase.splunk.com/app/2882/2.0.0/download`.

For any custom/internally developed apps, it's entirely up to your own workflow and how you choose to publish apps. Typically we use branch/dev builds and semantic versioning, something like the discussion here: https://github.com/splunk/splunk-ansible/issues/386#issuecomment-587606660

**Comment by westurner** [comment]
Got it. Thanks again
