### ISSUE TITLE
TASK [splunk_search_head : Check Splunk instance is running] is failing

### ISSUE THREAD

**Issue by dessyd** [splunk/docker-splunk#34]
When trying the advanced example:

`SPLUNK_COMPOSE=cluster_absolute_unit.yaml make sample-compose-up`

The task `TASK [splunk_search_head : Check Splunk instance is running]` is failing after 50 retries due to admin password failure.

I've set the password in the `defaults.yml` according to the doc but the deployment check is failing. 
Fortunately the cluster is deployed and I'm able to login using the admin credentials supplied in the `defaults.yml`.

When I used `bash` to check for Splunk container availability I did a more basic check:

```
wait_for_splunk_container ()
{
  port=$(docker port $1 8000)
  until $(curl --output /dev/null --silent --head --fail http://localhost:${port##*:});
  do
    printf '.'
    sleep 5
  done
  printf "\n"
}
```

that only looked for the Web service being available and not the ability to login which is potentially a different issue.

**Comment by arctan5x** [comment]
Below is the link to the actual play.
https://github.com/splunk/splunk-ansible/blob/master/roles/splunk_common/tasks/wait_for_splunk_instance.yml

For debugging, I would suggest ssh or exec into the container right after you run the make sample-compose-up command and run the same curl request as the ansible task to see what it actually complains about. Password setting happens way before checking Splunk instance is running and it might not be the issue. Also, if you have any additional logs, please post them here!

**Comment by dessyd** [comment]
After "bash"ing into the sh1 container I issued the following curl:
```
splunk@sh1:/$ curl --insecure --user admin:changeme  https://localhost:8000/services/server/info?output_mode=json

curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Comment by nwang92** [comment]
The 8000 port used by Splunk is the web port, which should only listen on HTTP. Based on the endpoint you're trying to hit, I think you should change the port from 8000 -> 8089, which is the management port that listens on HTTPS.

**Comment by dessyd** [comment]
The issue was due to an improper `default.yml` file
