### ISSUE TITLE
docker upgrade failure,  help please. 

### ISSUE THREAD

**Issue by kundeng** [splunk/docker-splunk#35]
I was using a splunk 7.1 with a volume container.   

I deleted the old splunk container and  try to do an upgrade like this:

docker run --hostname splunk --name splunk --volumes-from=vsplunk -p 8000:8000 -d -e "SPLUNK_START_ARGS=--accept-license --seed-passwd changeme --answer-yes" -e "SPLUNK_UPGRADE" -e "DEBUG"  splunk/splunk:latest

It failed.   Do I need to define any other environment variables? 

The error is:

      
WARNING: No password ENV var.  Stack may fail to provision if splunk.password is not set in ENV or a default.yml

 [WARNING]:  * Failed to parse /opt/ansible/inventory/environ.py with script

plugin: Inventory script (/opt/ansible/inventory/environ.py) had an execution

error:

 [WARNING]:  * Failed to parse /opt/ansible/inventory/environ.py with ini

plugin: /opt/ansible/inventory/environ.py:16: Expected key=value host variable

assignment, got: os

 [WARNING]: Unable to parse /opt/ansible/inventory/environ.py as an inventory

source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note

that the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************

Wednesday 10 October 2018  15:10:32 +0000 (0:00:00.051)       0:00:00.051 ***** 

ok: [localhost]

TASK [include_role : splunk_upgrade] *******************************************

Wednesday 10 October 2018  15:10:35 +0000 (0:00:02.829)       0:00:02.881 ***** 

fatal: [localhost]: FAILED! => {"msg": "The conditional check 'splunk.upgrade is defined' failed. The error was: error while evaluating conditional (splunk.upgrade is defined): 'splunk' is undefined\n\nThe error appears to have been in '/opt/ansible/site.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Upgrade role\n      ^ here\n"}

	to retry, use: --limit @/opt/ansible/ansible-retry/site.retry

PLAY RECAP *********************************************************************

localhost                  : ok=1    changed=0    unreachable=0    failed=1   

Wednesday 10 October 2018  15:10:35 +0000 (0:00:00.022)       0:00:02.904 ***** 

=============================================================================== 

Gathering Facts --------------------------------------------------------- 2.83s

include_role : splunk_upgrade ------------------------------------------- 0.02s

**Comment by amitmookerjee** [comment]
Hello,
You are required to provide the password in the command line. Take a look at https://github.com/splunk/docker-splunk/blob/master/README.md. Extract is shown below

 **Getting started
Use the following command to start a single instance of Splunk Enterprise:

 $> docker run -it -p 8000:8000 -e 'SPLUNK_START_ARGS=--accept-license' -e 'SPLUNK_PASSWORD=<password>' splunk-debian-9:latest start
Replace "<password>" with the initial password that you wish to use for logging into the Splunk admin user account. You can then access Splunk at http://localhost:8000 with those credentials.

Please note, the password supplied must conform to the default Splunk Enterprise password requirements.**

Thanks
Amit

**Comment by arctan5x** [comment]
Hi. You need to pass in a password using -e "SPLUNK_PASSWORD=<password>". Without SPLUNK_PASSWORD in either environment variable or a default yaml, the ansible inventory script will complain, and therefore, ansible would not be able to properly generate a set of variables.

Also Splunk Upgrade is used to not run any provisioning after the container starts. You need to pass SPLUNK_UPGRADE=True to make it work.

**Comment by lephino** [comment]
Please note, migration from 7.1 is not supported, and we DO NOT recommend migrating from the 7.1 container.   Please understand you are going down uncharted grounds, and while you may find success in the process, your installation is no longer valid for enterprise support.

**Comment by lephino** [comment]
I closed this issue as it's not a supported process or something we recommend.  You're welcome to continue chatting on this issue or opening a splunk answers post, but there is no work that will change to facilitate this migration.

**Comment by kundeng** [comment]
I HAVE included splunk_upgrade as an environment variable in the original  post.   But I understand  I am upgrading from 7.1 docker to 7.2.
