### ISSUE TITLE
Docker packaging of AppInspect?

### ISSUE THREAD

**Issue by gliptak** [splunk/docker-splunk#355]
Are there plans to officially package AppInspect using Docker?

https://dev.splunk.com/enterprise/downloads/

**Comment by nwang92** [comment]
This might be a better question for the AppInspect team but it's a bit out-of-scope for this project :) I will relay your question to a few folks internally though. 

(And if anyone on the Splunk AppInspect team is reading this, feel free to use this thread for any further questions/details).
