### ISSUE TITLE
forwarder serverName

### ISSUE THREAD

**Issue by csamarajeewa** [splunk/docker-splunk#372]
When starting the Forwarder in AWS Fargate, you cannot change the container name. So the logs have container id as the host name. I've tried setting multiple commands SPLUNK_CMD set servername or set default-hostname but it always registers the container id first which is a problem.

**Comment by nwang92** [comment]
I believe you can change this by adding the `hostname` field in the Fargate task definition: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html

**Comment by csamarajeewa** [comment]
I tried using the hostname but it looks like Fargate ignores it.

**Comment by csamarajeewa** [comment]
Hello Nelson,

The issue is hostname is not supported with awsvpc networking mode.

**Comment by nwang92** [comment]
Ah interesting, I wasn't aware of that. Could you try this workaround using the env var `SPLUNK_BEFORE_START_CMD`?
```
docker run -d -P -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=helloworld -e SPLUNK_BEFORE_START_CMD="set servername foobar" splunk/splunk:latest
```

**Comment by csamarajeewa** [comment]
Hello Nelson,

I tried that too but it will register the container id as the server name
first before showing the correct server name. So it shows 2 hosts every
time on splunk server. For the time being I had to initially start the
container with a fake splunk server and then use a command to add the real
one since it is executed at the end of the playbook.

Thanks

**Comment by nwang92** [comment]
Got it, I'll play around with Fargate a bit more and see if I can come up with anything else.

**Comment by nwang92** [comment]
I was able to change it reported hostname with the following `docker run` command:
```
docker run -d -P -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=helloworld -e SPLUNK_BEFORE_START_CMD="set default-hostname foobar,set servername foobar" splunk/splunk:latest
```

This changes the `${SPLUNK_HOME}/etc/system/local/inputs.conf` before Splunk starts to show something like:
```
[splunk@46669254230a local]$ cat inputs.conf
[default]
host = foobar
```
And it also changes the hostname of the server in `${SPLUNK_HOME}/etc/system/local/server.conf` to be:
```
[splunk@46669254230a local]$ cat server.conf
[general]
serverName = foobar
```

Upon Splunk starting, a search in `index=_internal | stats count by host` only shows 1 host reporting, which is just `foobar`.

**Comment by csamarajeewa** [comment]
Thanks
