### ISSUE TITLE
Possible documentation update

### ISSUE THREAD

**Issue by edumserrano** [splunk/docker-splunk#377]
Hi encountered the same as described in #324 but it was closed without further information.
It still took me a while to figure out what I was doing wrong so I thought it was worth it at least to add a reply to the closed issue.

I was wondering if you would feel useful a small PR to improve the docs with a warning on this? Perhaps even update to use the --mount instead of -v option which even produces an error message if the path used is not absolute instead of just doing a directory mount that the -v does.

Happy to do this if you think it's worth it.

**Comment by nwang92** [comment]
Yeah, any warnings or errors hit would be good to capture + note for future users :) I can make a quick docs PR by the end of the day, unless you beat me to it

**Comment by edumserrano** [comment]
Well done @nwang92 ! Thanks for picking this up.
