### ISSUE TITLE
client is getting rebooted while executing AnsiballZ_setup.py 

### ISSUE THREAD

**Issue by teja9415** [splunk/docker-splunk#392]
Hi Team,

we are facing the issue while running the playbook from server to client during the TASKS [Gathering Facts] machine is getting rebooted 

error message:- 

<machine_name> ESTABLISH SSH CONNECTION FOR USER: None
<machine_name> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/e5ff0330ca machine_name '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<machine_name> (0, '/root\n', '')
<machine_name> ESTABLISH SSH CONNECTION FOR USER: None
<machine_name> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/e5ff0330ca machine_name '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1594714923.07-182726791014688 `" && echo ansible-tmp-1594714923.07-182726791014688="` echo /root/.ansible/tmp/ansible-tmp-1594714923.07-182726791014688 `" ) && sleep 0'"'"''
<machine_name> (0, 'ansible-tmp-1594714923.07-182726791014688=/root/.ansible/tmp/ansible-tmp-1594714923.07-182726791014688\n', '')
<machine_name> Attempting python interpreter discovery
<machine_name> ESTABLISH SSH CONNECTION FOR USER: None
<machine_name> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/e5ff0330ca machine_name '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<machine_name> (0, 'PLATFORM\nLinux\nFOUND\n/usr/bin/python3.6\n/usr/bin/python2.7\n/usr/libexec/platform-python\n/usr/bin/python3\nENDFOUND\n', '')
<machine_name> ESTABLISH SSH CONNECTION FOR USER: None
<machine_name> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/e5ff0330ca machine_name '/bin/sh -c '"'"'/usr/bin/python3.6 && sleep 0'"'"''
<machine_name> (0, '{"platform_dist_result": ["redhat", "8.1", "Ootpa"], "osrelease_content": "NAME=\\"Red Hat Enterprise Linux\\"\\nVERSION=\\"8.1 (Ootpa)\\"\\nID=\\"rhel\\"\\nID_LIKE=\\"fedora\\"\\nVERSION_ID=\\"8.1\\"\\nPLATFORM_ID=\\"platform:el8\\"\\nPRETTY_NAME=\\"Red Hat Enterprise Linux 8.1 (Ootpa)\\"\\nANSI_COLOR=\\"0;31\\"\\nCPE_NAME=\\"cpe:/o:redhat:enterprise_linux:8.1:GA\\"\\nHOME_URL=\\"https://www.redhat.com/\\"\\nBUG_REPORT_URL=\\"https://bugzilla.redhat.com/\\"\\n\\nREDHAT_BUGZILLA_PRODUCT=\\"Red Hat Enterprise Linux 8\\"\\nREDHAT_BUGZILLA_PRODUCT_VERSION=8.1\\nREDHAT_SUPPORT_PRODUCT=\\"Red Hat Enterprise Linux\\"\\nREDHAT_SUPPORT_PRODUCT_VERSION=\\"8.1\\"\\n"}\n', '')
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<machine_name> PUT /root/.ansible/tmp/ansible-local-16707m0G0DP/tmplC2BDv TO /root/.ansible/tmp/ansible-tmp-1594714923.07-182726791014688/AnsiballZ_setup.py
<machine_name> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/e5ff0330ca '[machine_name]'
<machine_name> (0, 'sftp> put /root/.ansible/tmp/ansible-local-16707m0G0DP/tmplC2BDv /root/.ansible/tmp/ansible-tmp-1594714923.07-182726791014688/AnsiballZ_setup.py\n', '')
<machine_name> ESTABLISH SSH CONNECTION FOR USER: None
<machine_name> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/e5ff0330ca machine_name '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1594714923.07-182726791014688/ /root/.ansible/tmp/ansible-tmp-1594714923.07-182726791014688/AnsiballZ_setup.py && sleep 0'"'"''
<machine_name> (0, '', '')
<macchine_name> ESTABLISH SSH CONNECTION FOR USER: None
<machine_name> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/e5ff0330ca -tt machine_name '/bin/sh -c '"'"'/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1594714923.07-182726791014688/AnsiballZ_setup.py && sleep 0'"'"''
fatal: [machine_name]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: ", 
    "unreachable": true
}

ansible version:- 2.9.3

kindly let me know your inputs regarding the same

Thanks & regards,
Teja

**Comment by nwang92** [comment]
1. This might be a better issue here https://github.com/splunk/splunk-ansible/issues, since it seems like you're not using the Docker images at all here, if I'm understanding correctly
2. Could you share the command you're using that causes this?

It does not appear there are other errors until the end, where the machine returns unreachable. But there are steps in your sequence which shows that your client is able to successfully connect to the server and get some output, ex:
```
<machine_name> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/e5ff0330ca machine_name '/bin/sh -c '"'"'/usr/bin/python3.6 && sleep 0'"'"''
<machine_name> (0, '{"platform_dist_result": ["redhat", "8.1", "Ootpa"], "osrelease_content": "NAME=\"Red Hat Enterprise Linux\"\nVERSION=\"8.1 (Ootpa)\"\nID=\"rhel\"\nID_LIKE=\"fedora\"\nVERSION_ID=\"8.1\"\nPLATFORM_ID=\"platform:el8\"\nPRETTY_NAME=\"Red Hat Enterprise Linux 8.1 (Ootpa)\"\nANSI_COLOR=\"0;31\"\nCPE_NAME=\"cpe:/o:redhat:enterprise_linux:8.1:GA\"\nHOME_URL=\"https://www.redhat.com/\\"\\nBUG_REPORT_URL=\\"https://bugzilla.redhat.com/\\"\\n\\nREDHAT_BUGZILLA_PRODUCT=\\"Red Hat Enterprise Linux 8\"\nREDHAT_BUGZILLA_PRODUCT_VERSION=8.1\nREDHAT_SUPPORT_PRODUCT=\"Red Hat Enterprise Linux\"\nREDHAT_SUPPORT_PRODUCT_VERSION=\"8.1\"\n"}\n', '')
```

**Comment by teja9415** [comment]
Thanks for quick response we got the issue 

sorry for inconvenience 

Regards,
Teja.
