### ISSUE TITLE
expose splunk thru k8s ingress

### ISSUE THREAD

**Issue by alnhk** [splunk/docker-splunk#397]
Hello:

Here's the tech stacks i am using :
1. AWS EKS 1.16
2. Deployed "splunk/splunk:latest" to EKS using default - "SPLUNK_START_ARGS=--accept-license"

I used statefulset and service, with service (loadbalancer enabled), i am able to directly access it from my laptop, however with ingress enabled, it is not happening. Even I created  route53 pointing to service (load balancer AWS), still not able to access. 

I also created "hello world" (contianing statefulset, service and ingress), i am able to open,. Kindly  let me know if anything is to be corrected  when using ingress ?

**Comment by nwang92** [comment]
Could you share your ingress definition?

**Comment by alnhk** [comment]
> Could you share your ingress definition?

@nwang92 : 

> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   name: splunk-ingress
>   annotations:
>     kubernetes.io/ingress.class: "nginx"
> spec:
>   rules:
>     - host: splunk.example.com
>       http:
>         paths:
>           - path: /
>             backend:
>               serviceName: splunk-service
>               servicePort: 8000

**Comment by nwang92** [comment]
So far I haven't had much success reproducing this. I've been using the following:
```
$ cat nginxing.yml
controller:
  ingressClass: nginxdemo

  admissionWebhooks:
    enabled: false

  service:
    annotations:
      # My VPC is internal, so this was required for the ELB
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0

$ helm -n default install my-release ingress-nginx/ingress-nginx -f nginxing.yml
```
```
$ cat splunk.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: so1
  labels:
    app: splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
        - name: so1
          image: splunk/splunk:latest
          env:
            - name: SPLUNK_PASSWORD
              value: helloworld
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: DEBUG
              value: "true"
          ports:
            - name: web
              containerPort: 8000
          volumeMounts:
            - mountPath: /opt/splunk/var
              name: splunk-data
      volumes:
      - name: splunk-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: splunk-service
  labels:
    app: splunk
spec:
  selector:
    app: splunk
  ports:
    - name: splunkweb
      port: 8000
      targetPort: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginxdemo
  name: so1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: splunk-service
          servicePort: 8000
        path: /

$ kubectl apply -f splunk.yml
```

I'm able to successfully access my Splunk instance through the root path of the load balancer created via the nginx ingress controller. I omitted the `host` directive in the ingress because I didn't want to touch any DNS settings right now.

If you omit your `host: splunk.example.com` line, does it work? If so, then the error is likely with how your DNS is configured and wired up to use whatever hostname you can pinning the ingress controller to route requests to.

**Comment by nwang92** [comment]
Going to close this due to inactivity, but feel free to re-open or comment if you're still having issues.
