### ISSUE TITLE
Bug: Splunk slack channel guidance incorrect

### ISSUE THREAD

**Issue by henricook** [splunk/docker-splunk#407]
The README says that support is available on the Splunk slack channel with this text:

`Join the #docker room in the Splunk Slack channel`

But it seems signup is limited to only a small handful of companies, so this support method is useless to most of us customers

**Comment by nwang92** [comment]
Ah I wasn't aware of this - let me look into it and see why this is the case.

**Comment by nwang92** [comment]
Do you mean the sign-up here restricted? https://docs.splunk.com/Documentation/Community/1.0/community/Chat

I'm not certain how the Slack is moderated, but if you're a customer you should be able to join via http://splk.it/slack? If not, I can certainly add this as a note/caveat but I guess was under the impression this was a little more open than it actually is :(

**Comment by henricook** [comment]
I didn't know about splk.it/slack - nice one. How's this look for a README amendment? https://github.com/splunk/docker-splunk/pull/409
