### ISSUE TITLE
Usage / help text examples missing SPLUNK_PASSWORD 

### ISSUE THREAD

**Issue by mkinsley** [splunk/docker-splunk#414]
*Description*

3 out of 4  docker cli example in the usage message don't include SPLUNK_PASSWORD.  SPLUNK_PASWORD is not included in the list of ENV VARS that are of importance. 

*Expect*

- usage examples should work

*Observed*

- usage message is printed when SPLUNK_START_ARGS missing (awesome!)
- 3 out of 4 examples do not include SPLUNK_PASSWORD ENV vars
- SPLUNK_PASSWORD is not called out int the Environment Variables section

<img width="1980" alt="Screen Shot 2020-08-27 at 1 29 48 PM" src="https://user-images.githubusercontent.com/2430045/91492056-cf93c700-e869-11ea-9291-f2325a54e394.png">

**Comment by circa10a** [comment]
@mkinsley Since docs were updated, good to close this one?

**Comment by nwang92** [comment]
Closing due to staleness.
