### ISSUE TITLE
Question: Can the container be started with a forwarder license ?

### ISSUE THREAD

**Issue by VincentC75** [splunk/docker-splunk#421]
I start a container as a heavy forwarder:

`docker run -d -p 8000:8000 -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=mydummypw" -e "SPLUNK_ROLE=splunk_heavy_forwarder" --name hforwarder splunk/splunk:latest`

When I connect to it and check the license used with `splunk list licenser-groups` it shows a trial license.
I would like to use a forwarder license instead. I there any way I can do that with a startup parameter ?

If I add SPLUNK_LICENSE_MASTER_URL to make it a slave to a license server it works, but I did not find a way to use the Forwarder license group.

**Comment by VincentC75** [comment]
Got around it with `docker run -d -p 8000:8000 -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=mydummypw" -e "SPLUNK_ROLE=splunk_heavy_forwarder" -e "SPLUNK_BEFORE_START_CMD=edit licenser-groups Forwarder -is_active 1" --name hforwarder splunk/splunk:latest`

I didn't know this SPLUNK_BEFORE_START_CMD variable existed.

**Comment by alexeiser** [comment]
For others finding this - an alternative is to use:
`-e SPLUNK_LICENSE_URI="forwarder"`
