### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by irom77** [splunk/docker-splunk#424]
Getting for redhat-8 or  debian-10, but not for debian-9 or centos-7 ?

`SSLError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))`

**Comment by nwang92** [comment]
Could you share where/how you're seeing this?

**Comment by irom77** [comment]
Hm..I tried 'make splunk-py23-debian-10' again and it worked...'Successfully tagged splunk-py23-debian-10:latest'
