### ISSUE TITLE
Python 2.7 EOL

### ISSUE THREAD

**Issue by dp-42** [splunk/docker-splunk#428]
Hello,

I noticed each time you start a container the following warning:
```
/usr/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
ansible-playbook 2.9.13
  config file = /opt/ansible/ansible.cfg
  configured module search path = [u'/opt/ansible/library', u'/opt/ansible/apps/library', u'/opt/ansible/ansible_commands']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Oct 30 2019, 17:37:16) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```
It seems the Ansible version utilized in this project still uses Python 2.7 and that version is [End Of Life](https://www.python.org/doc/sunset-python-2/).

Now I wanted to ask if there are any specific reasons why this version is used and if there are any plans to update to 3.x?

Many thanks!

**Comment by nwang92** [comment]
That's part of our roadmap!

**Comment by dp-42** [comment]
Sorry, for the late reply!

Do you have any rough schedule when this planned?

Would you prefer to keep that issue open or should I close it?

**Comment by nwang92** [comment]
Let's keep the issue open - I'm hoping to get something out before the end of the year.
