### ISSUE TITLE
Clarify kernel support 

### ISSUE THREAD

**Issue by eddikay** [splunk/docker-splunk#429]
There is customer confusion about kernel support as listed in the support.md file. It currently states: Kernel version 4.0 or higher. What this means is any version 4.x kernel is supported. But some customers are inferring 5.x kernel support from "4.0 or higher" statement.
Can you change the support.md to "Kernel version 4.x" or something similar. And after 5.x kernel support is added, it can be updated to "Kernel version 4.x, 5.x" or equivalent. 
Thanks.

**Comment by nwang92** [comment]
👍 

We can update the docs to be more explicit in these semantics; I think we do point to [Splunk's system requirements](https://docs.splunk.com/Documentation/Splunk/8.1.0/Installation/Systemrequirements#Unix_operating_systems) somewhere, which at the moment says 5.x is not supported.

**Comment by eddikay** [comment]
Indeed, there's no 5.x kernel support yet. On that linked page, you can see we use the structure of "Linux 4.x kernel versions," and I'm only looking for consistency. Thanks again!
