### ISSUE TITLE
No more debian images

### ISSUE THREAD

**Issue by bai** [splunk/docker-splunk#439]
👋 It looks like starting with Splunk 8.1.0 debian images are [no longer available](https://hub.docker.com/r/splunk/splunk/tags?page=1&ordering=last_updated&name=8.1) on Docker Hub. I was wondering if it's intentional and debian is no longer supported?

/cc @rfaircloth-splunk @alishamayor

**Comment by berlincount** [comment]
yeah, I'm having the same problem. have been waiting for a few weeks for the new release to pop up, to no avail. 🤷‍♂️

**Comment by alishamayor** [comment]
Yes, as of 8.1.0 we are no longer releasing for Debian for security reasons. Please use the RHEL images from now on.

**Comment by bai** [comment]
Thanks for clarifying 🙏

**Comment by berlincount** [comment]
Wow.

tbh, I‘d have expected some kind of advance warning or anything - not everyone has RHEL experience, and some people are using Debian _because_ of security reasons and established workflows (if only to address `splunk-ansible` shortcomings).

I respectfully have to push back on this change and request prolonged support of Debian Docker images to allow for integration changes and integration testing.

**Comment by berlincount** [comment]
(please reopen this issue until this has been addressed)

**Comment by nwang92** [comment]
Thanks for catching this - I thought there were external communication on this done through Splunk Docs but I'm having trouble finding it myself. In any case, this is something we should've announced or mentioned in our change logs or documentation. Apologies for this!

Let me route this to the PM and get some clarifying information on this.

**Comment by pogdin** [comment]
We did communicate this change [here](https://www.splunk.com/en_us/blog/it/an-insider-s-guide-to-splunk-on-containers-and-kubernetes.html) but I can understand how that could have been missed given that it was not in the usual locations for Splunk platform deprecation in Splunk docs.

**Comment by berlincount** [comment]
Okay - that indeed could be easily missed.

How long can the window to change be extended, and when can Docker images for the Splunk versions released during that window be expected?

**Comment by alishamayor** [comment]
@berlincount I've just posted the Debian images for 8.1. You should see them [on Docker Hub](https://hub.docker.com/r/splunk/splunk/tags?page=1&ordering=last_updated&name=8.1) now.

We're planning to deprecate Debian images in the Spring of 2021 and will be sure to make it absolutely clear within our docker-splunk docs. Apologies again for the confusion, and thank you for being patient with us!

**Comment by berlincount** [comment]
Thank you very much for the quick turnaround and for a reliable timeline! :)

**Comment by alishamayor** [comment]
I definitely recommend reading [An Insider’s Guide to Splunk on Containers and Kubernetes](https://www.splunk.com/en_us/blog/it/an-insider-s-guide-to-splunk-on-containers-and-kubernetes.html) if you haven't yet (also linked by @pogdin above). It's a little old but does well to outline our decision-making.

**Comment by alishamayor** [comment]
@berlincount Just a note that it's officially that time. The next release (8.2.0) will not include Debian images.
