### ISSUE TITLE
Can't restart splunk docker after ubuntu upgrade

### ISSUE THREAD

**Issue by SirTerrific** [splunk/docker-splunk#45]
VM Ubuntu 16.04

I use a splunk docker on en VM ubuntu. After the upgrade, I restarted the VM but splunk docker can't start.

splunk    | Friday 19 October 2018  03:09:30 +0000 (0:00:41.411)       0:00:41.565 ******** 
splunk    | =============================================================================== 
splunk    | Gathering Facts -------------------------------------------------------- 41.41s
splunk    |  [WARNING]: provided hosts list is empty, only localhost is available. Note
splunk    | that the implicit localhost does not match 'all'
splunk    | 
splunk    | 
splunk    | PLAY [localhost] ***************************************************************
splunk    | 
splunk    | TASK [Gathering Facts] *********************************************************
splunk    | Friday 19 October 2018  03:09:40 +0000 (0:00:00.197)       0:00:00.198 ******** 
splunk    | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TimeoutError: Timer expired after 10 seconds
splunk    | fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2", "msg": "Timer expired after 10 seconds", "rc": 257}
splunk    | 	to retry, use: --limit @/opt/ansible/ansible-retry/site.retry
splunk    | 
splunk    | PLAY RECAP *********************************************************************
splunk    | localhost                  : ok=0    changed=0    unreachable=0    failed=1   
splunk    | 
splunk    | Friday 19 October 2018  03:09:59 +0000 (0:00:19.578)       0:00:19.777 ******** 
splunk    | =============================================================================== 
splunk    | Gathering Facts -------------------------------------------------------- 19.58s
splunk exited with code 2

All worked well before.
Do you have any ideas?

**Comment by bb03** [comment]
@SirTerrific Taking a look at this now. Can you give me more information about the workflow used.  The title says you were restarting the container and the contents say you were starting it.  I want to make sure that I get the exact workflow down.

**Comment by bb03** [comment]
Here's the environment that I tested on.
```$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
```
I did not have any issues in this environment.  More details about your error would be nice, thank you!

**Comment by bb03** [comment]
Under the environment listed, could not reproduce the issue. Seemed to run fine.

**Comment by SirTerrific** [comment]
I was using a VM on HyperV v1 and it's seem that the hypervisor is the problem. I tried with a debian, ubuntu and alpine and I had the same issue with the splunk 7.2 docker. I installed on a non Virtualize system with the same OS' and all works. So with the VM, I'm able to use the 7.1.2 docker with alpine OS as host and all work great.
