### ISSUE TITLE
SPLUNK_DEFAULTS_URL with Azure Devops Repo not working

### ISSUE THREAD

**Issue by vinitmasaun** [splunk/docker-splunk#471]
Hello,

I am unable to use an Azure Devops Repo url to retrieve the defaults.yml file when passing the url as a value for the SPLUNK_DEFAULTS_URL var. The container starts but the ansible play doesn't start to install and configure the splunk forwarder. I am using the latest splunkuniveralforwarder image.   If I provision it via the example nginx webserver pod http://splunk-defaults/ it works.  For Azure Devops repo I need to authenticate with an Authorization token passed in the header.  How can I pass the Authorization token as header in the SPLUNK_DEFAULTS_URL?

**Comment by nwang92** [comment]
I can add something to enable this. Out of curiosity, would this be an ephemeral token or a static auth token? And are you comfortable with having auth tokens exposed as env vars? I don't know too much about the Azure Devops, but just trying to see what can be done here while still preserving any access permissions.

**Comment by vinitmasaun** [comment]
> I can add something to enable this. Out of curiosity, would this be an ephemeral token or a static auth token? And are you comfortable with having auth tokens exposed as env vars? I don't know too much about the Azure Devops, but just trying to see what can be done here while still preserving any access permissions.

The Preference is for ephemeral but we can use a static token.  We can mask the tokens as secrets in our build process so the actual token wont be exposed.

**Comment by nwang92** [comment]
Per the above PR, I added the `SPLUNK_DEFAULTS_HTTP_AUTH_HEADER` environment variable for this ask. This should be available in `splunk/splunk:edge` now.

**Comment by vinitmasaun** [comment]
> Per the above PR, I added the `SPLUNK_DEFAULTS_HTTP_AUTH_HEADER` environment variable for this ask. This should be available in `splunk/splunk:edge` now.

Thank you!  so, is this env variable now available for the splunk/universalforwarder:latest image as well?

**Comment by nwang92** [comment]
It should also be available on `splunk/universalforwarder:edge`, but not `latest` yet.

**Comment by vinitmasaun** [comment]
> It should also be available on `splunk/universalforwarder:edge`, but not `latest` yet.

Just tried it by passing the following env variables in the container spec yml but the splunk uf container hangs at the start of the ansible play and eventually restarts with the same hung state:

- name: SPLUNK_START_ARGS
   value: --accept-license
- name: SPLUNK_DEFAULTS_HTTP_AUTH_HEADER
   value: my Personal Access Token value
- name: SPLUNK_DEFAULTS_URL
   value: 'https://dev.azure.com/org/repoarea/_apis/git/repositories/myrepo/items?path=%2FSplunk%2Fdefault.yml&api-version=6.0'


I am able to curl the above ADO REST URL from the splunk uf container but the ansible play is not able to get the yml.

**Comment by nwang92** [comment]
You may potentially need to specify the token type? The value of `SPLUNK_DEFAULTS_HTTP_AUTH_HEADER` gets set to the "Authorization" header of the request, which may mean you need to also add "Bearer" or "Basic" as needed.

For example, I'm using the following containers from this [basic-auth reference](https://hub.docker.com/r/beevelop/nginx-basic-auth/):
```bash
# set a dummy password
$ cat default.yml
---
splunk:
  password: qwerty12345
  
# launch a container with a fetchable default.yml
$ docker run -d -P --name web -v `pwd`/default.yml:/www/default.yml dockercloud/hello-world

# add basic auth proxy with credentials "foo:bar"
$ docker run -d -p 80:80 --link web:web --name auth beevelop/nginx-basic-auth

# generate basic auth header value
$ echo -n foo:bar | base64
Zm9vOmJhcg==

# launch splunk with correct env vars
$ docker run -d -P -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_DEFAULTS_URL=http://auth/default.yml -e SPLUNK_DEFAULTS_HTTP_AUTH_HEADER="Basic Zm9vOmJhcg==" --link auth:auth splunk/splunk:edge

# log into splunkweb using admin:qwerty12345
```
