### ISSUE TITLE
World writeable file

### ISSUE THREAD

**Issue by dlaidlaw** [splunk/docker-splunk#476]
The docker container contains a world writeable file: 
```
/opt/splunk-etc/apps/splunk_secure_gateway/lib/past/builtins/noniterators.py
```
This causes issues when certifying the container with CIS Security benchmarks. Any chance of getting the permissions on that file changed so that is it not world writeable?

**Comment by nwang92** [comment]
I'll take a look, thanks for reporting this!

**Comment by nwang92** [comment]
This is actually coming from the 8.1.3 package itself - I've bubbled this up to our internal product security team to review, but it should be fixed in a future version.
