### ISSUE TITLE
journalctl in base-redhat-8 uf image

### ISSUE THREAD

**Issue by MikeTomlin19** [splunk/docker-splunk#477]
Can we have the option to include journalctl and it's dependencies in the universal forwarder image?  This would allow the journald scripts that come in the *nix app to work from within this container.

**Comment by dilipbravo** [comment]
@matthewmodestino  can you assist here ..?

**Comment by nwang92** [comment]
Let me take a look!

**Comment by matthewmodestino** [comment]
hmm 🤔 what is the nix app input doing exactly? Also will the docker image even see the journal you are after? Are you trying to collect from the a docker/k8s node's journal??

Newer versions of Splunk have native journal inputs now, can this be used instead? I guess this may also require journalctl?

https://docs.splunk.com/Documentation/Splunk/8.1.3/Data/CollecteventsfromJournalD

Will let Nelson handle looking and having to bundle more libs in, this gets tricky with vuln scans and support.

**Comment by MikeTomlin19** [comment]
@matthewmodestino I mixed up the nix app and the journald modular input - the latter is what we're trying to get working within this pod.

We'd like to get the underlying node's journald logs.  I was able to hack the journalctl command to work within a splunk uf pod by mounting the host's /var/log dir, its journalctl binary, all of its lib dependencies and adding the "--directory /var/log/journal" flag to all journalctl commands.

Because the splunk UF image is built with the ubi 8 minimal image, it isn't systemd based, so attempts to layer it in on top have not worked.

**Comment by nwang92** [comment]
Looks like `journalctl` only comes from the entire [systemd package](https://centos.pkgs.org/8/centos-baseos-x86_64/systemd-239-41.el8_3.1.x86_64.rpm.html) and can't be installed by itself.

My only concern is the heaviness of including systemd in docker, without actually needing all that it provides. There's also some additional size it adds, which seems like a lot of just `journalctl`:
```
base-redhat-8-systemd                      latest                    3ed87ab58d82   8 minutes ago   401MB
base-redhat-8                              latest                    4bf2e2f59645   39 hours ago    369MB
```

I'll cut a branch with it and see if it works. I'm also concerned with Matthew's comments around if journald within the container can successfully access the host's systemd-journald. I imagine you'll still need to mount `/var/log` and maybe include that extra `--directory` flag?

**Comment by MikeTomlin19** [comment]
Thank you @nwang92 ! Yes, I'd still need to mount /var/log/journal and point journalctl there. I understand the concern on the sizing and increased attack surface area. It's too bad journalctl isn't decoupled from systemd.
