### ISSUE TITLE
splunk universal forwarder - no users exist

### ISSUE THREAD

**Issue by ruivapps** [splunk/docker-splunk#49]
trying to following the documentation from: https://github.com/splunk/docker-splunk/blob/master/documentation/SETUP.md

successful 
`docker pull splunk/universalforwarder:latest`
faiiled
`docker run -d  -p 9997:9997 -e 'SPLUNK_START_ARGS=--accept-license' -e 'SPLUNK_PASSWORD=1234' splunk/universalforwarder:latest`

docker logs
`fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/opt/splunkforwarder/bin/splunk", "enable", "listen", "9997", "-auth", "admin:1234", "--accept-license", "--answer-yes", "--no-prompt"], "delta": "0:00:00.618205", "end": "2018-10-29 16:01:44.732552", "failed_when_result": true, "msg": "non-zero return code", "rc": 24, "start": "2018-10-29 16:01:44.114347", "stderr": "No users exist. Please set up a user.", "stderr_lines": ["No users exist. Please set up a user."], "stdout": "", "stdout_lines": []}
`

```
# docker --version
Docker version 18.06.1-ce, build e68fc7a
# docker images|grep universalforwarder
splunk/universalforwarder                  latest              3b40b5f5d4a8        4 weeks ago         208MB
```

**Comment by lephino** [comment]
The password needs to be larger than the splunk minimum requirement (think it's 8 right now), just set your password to "123456789" and you should be fine.

**Comment by ruivapps** [comment]
thanks for the reply. 

yes, it works after update password length, hope logs would have better error explanation of error. (instead no users exist, maybe says password not meet minimum requirement)

**Comment by lephino** [comment]
we did add some better logging on the error and on the rebuild this will be much better.

**Comment by ruivapps** [comment]
super!
