### ISSUE TITLE
Images have wrong Tags

### ISSUE THREAD

**Issue by marcusschiesser** [splunk/docker-splunk#562]
Looks like there is a BIG problem with the build process for the docker images. They have wrong tags. Tag 8.2.9 is actually version 8.1.12:

When I download an 8.2.9 image from scratch (I deleted it first locally):
```
$ docker run -it --entrypoint=/bin/bash splunk/splunk:8.2.9
Unable to find image 'splunk/splunk:8.2.9' locally
8.2.9: Pulling from splunk/splunk
...
```
Then I just run ansible:
```
[ansible@20c9d65ff4a6 splunk]$ SPLUNK_START_ARGS=--accept-license SPLUNK_PASSWORD=changeme /sbin/entrypoint.sh start-and-exit;
...
```
I am actually getting 8.1.12:
```
[ansible@20c9d65ff4a6 splunk]$ sudo bin/splunk version
Splunk 8.1.12 (build 4eb558a8f0b7)
```
Can someone please have a look into this - it impacts a couple of instances on my K8S cluster.

**Comment by pogdin** [comment]
Verified.

**Comment by alishamayor** [comment]
Thanks for bringing this to our attention. We've fixed the broken pipeline and the images are now tagged correctly.
