### ISSUE TITLE
Missing Images for 9.0.6 and 9.1.1

### ISSUE THREAD

**Issue by hanswurscht** [splunk/docker-splunk#622]
Hi,

dockerhub is currently still missing images for the new versions 9.0.6 and 9.1.1 of splunk enterprise.

Please publish them there, as the new versions contain fixes for several cricitcal security issues.

Thanks!

**Comment by flaken2000** [comment]
Hi,

I see the Splunk Enterprise 9.0.6 and 9.1.1 images are now available on dockerhub. But those versions of the universalforwarder image are still missing.

On August 30th Splunk published new advisories and immediately made available new binaries (8.2.12, 9.0.6, and 9.1.1) to fix those security vulnerabilities.

Meanwhile 12 days later those versions of the universal forwarder images have yet to be published. Why the delay?

Thanks.

**Comment by adityapinglesf** [comment]
UF 9.1.x images have been released.
