### ISSUE TITLE
Can't start latest/9.0.9 version

### ISSUE THREAD

**Issue by vtsvetkov-splunk** [splunk/docker-splunk#660]
We use `latest` tag for running in our CI pipelines. It started failing recently. I realized that [latest](https://hub.docker.com/layers/splunk/splunk/latest/images/sha256-05c376ef33faf559162a7621c3ffc184d4ce09f768a4ff670b43a5fdadc0561d?context=explore) tag points to [9.0.9](https://hub.docker.com/layers/splunk/splunk/9.0.9/images/sha256-05c376ef33faf559162a7621c3ffc184d4ce09f768a4ff670b43a5fdadc0561d?context=explore) instead of 9.2.1

<img width="604" alt="image" src="https://github.com/splunk/docker-splunk/assets/142901247/d359eba9-d31f-45b1-8a6f-bb1695eaf3f1">

Then I tried to spin up the version 9.0.9 and got the same error as on CI:

<details><summary>Errors during Splunk initialization</summary>
<p>

   failed: [localhost] (item={'key': '/servicesNS/nobody/splunk_instrumentation/admin/telemetry/general', 'value': 'showOptInModal=0&optInVersionAcknowledged=4'}) => {
       "ansible_loop_var": "item",
       "changed": false,
       "item": {
           "key": "/servicesNS/nobody/splunk_instrumentation/admin/telemetry/general",
           "value": "showOptInModal=0&optInVersionAcknowledged=4"
       }
   }
   
   MSG:
   
   POST/servicesNS/nobody/splunk_instrumentation/admin/telemetry/generaladmin********8089{'showOptInModal': '0&optInVersionAcknowledged=4'}NoneNone[200, 201, 409];;; AND excep_str: URL: https://127.0.0.1:8089/servicesNS/nobody/splunk_instrumentation/admin/telemetry/general; data: {"showOptInModal": "0&optInVersionAcknowledged=4"}, exception: API call for https://127.0.0.1:8089/servicesNS/nobody/splunk_instrumentation/admin/telemetry/general and data as {'showOptInModal': '0&optInVersionAcknowledged=4'} failed with status code 400: <?xml version="1.0" encoding="UTF-8"?>
   <response>
     <messages>
       <msg type="ERROR">Argument "{"showOptInModal": "0" is not supported by this handler.</msg>
     </messages>
   </response>
   , failed with status code 400: <?xml version="1.0" encoding="UTF-8"?>
   <response>
     <messages>
       <msg type="ERROR">Argument "{"showOptInModal": "0" is not supported by this handler.</msg>
     </messages>
   </response>
   
   failed: [localhost] (item={'key': '/servicesNS/admin/search/data/ui/ui-tour/search-tour', 'value': 'tourPage=search&viewed=1'}) => {
       "ansible_loop_var": "item",
       "changed": false,
       "item": {
           "key": "/servicesNS/admin/search/data/ui/ui-tour/search-tour",
           "value": "tourPage=search&viewed=1"
       }
   }
   
   MSG:
   
   POST/servicesNS/admin/search/data/ui/ui-tour/search-touradmin********8089{'tourPage': 'search&viewed=1'}NoneNone[200, 201, 409];;; AND excep_str: URL: https://127.0.0.1:8089/servicesNS/admin/search/data/ui/ui-tour/search-tour; data: {"tourPage": "search&viewed=1"}, exception: API call for https://127.0.0.1:8089/servicesNS/admin/search/data/ui/ui-tour/search-tour and data as {'tourPage': 'search&viewed=1'} failed with status code 400: <?xml version="1.0" encoding="UTF-8"?>
   <response>
     <messages>
       <msg type="ERROR">Argument "{"tourPage": "search" is not supported by this handler.</msg>
     </messages>
   </response>
   , failed with status code 400: <?xml version="1.0" encoding="UTF-8"?>
   <response>
     <messages>
       <msg type="ERROR">Argument "{"tourPage": "search" is not supported by this handler.</msg>
     </messages>
   </response>

</p>
</details> 

Reproduction: 
https://github.com/vtsvetkov-splunk/crispy-fishstick/actions/runs/8484825990/job/23248480607#step:2:578
The workflow: 
https://github.com/vtsvetkov-splunk/crispy-fishstick/actions/runs/8484825990/workflow

**Comment by vtsvetkov-splunk** [comment]
@jmeixensperger it is still reproducible
https://github.com/vtsvetkov-splunk/crispy-fishstick/actions/runs/9110279341/job/25044978465#step:2:578

Linking the same issue - https://github.com/splunk/docker-splunk/issues/667

**Comment by vtsvetkov-splunk** [comment]
@jmeixensperger any ETA for fixing this?

**Comment by jmeixensperger** [comment]
@vtsvetkov-splunk Sorry I did not mean to close this--it should be fixed once the next release goes out.

**Comment by vtsvetkov-splunk** [comment]
It works fine with 9.1 and 9.2. The `latest` points to `9.2`. Thank you!
