### ISSUE TITLE
Python 3.7 EOL

### ISSUE THREAD

**Issue by PA7R14RCH** [splunk/docker-splunk#661]
Just curious with Python 3.7 EOL, is there a plan moving forward to upgrade? I know 3.8 is also close to EOL. 

I recognize all the other issues, this would be low priority, just looking to project my own projects and answer management concerns for the SIEM.

**Comment by jmeixensperger** [comment]
We are planning an upgrade to Python 3.9 very soon. See: https://github.com/splunk/docker-splunk/pull/677

**Comment by PA7R14RCH** [comment]
Issue addressed in #677
