### ISSUE TITLE
Repeatedly returning to the login page: "Your session has expired.  Log in..."

### ISSUE THREAD

**Issue by GrahamHannington** [splunk/docker-splunk#68]
With apologies if this is a Splunk (Web) issue, rather than an issue with this Splunk Docker image...

Embarrassing disclosure: Some careless fool overfed my local Windows install of Splunk too many times, so I'm now testing my Splunk dashboards entirely in Docker containers. I might be that fool; several users forward data from the same source, and I haven't bothered trying to identify which people were responsible for those particular "feeding times".

I'm starting Splunk Enterprise 7.2.0 with the Trial license in Docker containers. Sometimes, Splunk Web repeatedly returns to the login page. I've previously solved that, or thought I had, by deleting the cookies for that Splunk Web instance (using Chrome developer tools) and logging in again. However, last time this happened (a couple of days ago), that didn't work. So I restarted Chrome. That worked. Phew. It's unsettling, though. I wish I better understood why it was happening. And why deleting those cookies seemed to work before, without restarting my browser.

I should confess, in case it's significant, that I sometimes have multiple tabs open to the same and different instances of Splunk Web (different port numbers—different Docker containers—running on the same Docker host; sometimes, different hosts, too).

Any ideas?

I understand that switching Splunk inside the containers to a Splunk Free license would make this issue go away. If it's possible to use this Splunk Docker image to start a container as Splunk Free—rather than starting as Enterprise Trial, and then having to switch to a Free license—that would be useful.

**Comment by lephino** [comment]
are you running multiple containers on the same host?  If so, the session-key cookie will break as it's tracked by the url of the host.

**Comment by GrahamHannington** [comment]
> are you running multiple containers on the same host?

Yes.

Each container uses a different set of port numbers. For example, for Splunk Web:

`http://myhost:18000/`

`http://myhost:28000/`

> If so, the session-key cookie will break as it's tracked by the url of the host.

Sorry, I don't know what you mean by "url of the host".

I understand the terms hostname, port, and URL.

From one of the example URLs I quoted above:

* The hostname is `myhost`
* The port is `18000`
* The Splunk Web URL is `http://myhost:18000/`. By [definition](https://en.wikipedia.org/wiki/URL), the URL _includes_ the port.

In Google Chrome developer tools, I see this:

![image](https://user-images.githubusercontent.com/8519708/49321901-939bc880-f502-11e8-85f4-9d568de193de.png)

Are you saying that Splunk Web session tracking does not distinguish between URLs with the same hostname but different ports?

**Comment by lephino** [comment]
your cookies are a little deceiving, the cookies you have are actually "session_id_8000, splunkd_8000" etc, they aren't segregated.  To splunk internal to a container, the session_id was created for the port splunk_web think's it's running on.  In your case, the issue is that splunk is being proxied to 18000, and the cookie stores the wrong port.  Splunk supports running on any port, but this problem frequently happens when it's behind a LB or docker / proxy.  Splunk has some internal SPL's open to address this issue, but until those are resolved, this issue will happen anytime you run multiple splunk on the same host. 
![screen shot 2018-12-05 at 6 12 21 pm](https://user-images.githubusercontent.com/2249857/49554410-55fbbe80-f8b9-11e8-816a-bd468ce1a778.png). Sorry for the inconvenience this causes!

**Comment by GrahamHannington** [comment]
> Splunk has some internal SPL's open to address this issue, but until those are resolved, this issue will happen anytime you run multiple splunk on the same host.

Ouch! Thanks for the clarification, much appreciated.

I was wrong about this:

> switching Splunk inside the containers to a Splunk Free license would make this issue go away.

because I've just experienced this issue with Splunk Free.

The bleeding obvious: this is a real gotcha for anyone using this Splunk Docker image. This behavior is Docker-unfriendly:

> this issue will happen anytime you run multiple splunk on the same host.

**Comment by GrahamHannington** [comment]
I'm not sure what to write about this restriction in the user documentation for my Docker image.

"Don't run more than one Splunk container on the same Docker host"?!

That sounds to me like a (bad) joke; completely contrary to the idea of Docker containers.

Any suggestions?

Would you consider adding a corresponding item to the [Troubleshooting](https://github.com/splunk/docker-splunk/blob/develop/docs/TROUBLESHOOTING.md) topic? (I'm imagining myself as a new user of my Docker image, reading about that restriction, and thinking, "Wait, that can't be true. What do the developers of the base Splunk Docker image have to say about this?")

**Comment by GrahamHannington** [comment]
A local colleague has just looked at this issue, and suggested something I wish I'd thought of: when you start a Docker container, pass an environment variable that sets the Splunk Web port.

We looked at the table of supported environment variables under the documentation heading "[Environment variables for Splunk instance](https://splunk.github.io/splunk-ansible/ADVANCED.html#environment-variables-for-splunk-instance)", but that table did not list a corresponding environment variable.

We tried this anyway:

    docker run -d -e SPLUNK_HTTP_PORT=8001 ... -p 8500:8001 ...

Yep, that worked. Browsing to `http://myhost:8500` shows Splunk Web.

We opened a second tab in the same browser to another instance of Splunk Web on a different port of the same host, where the Splunk Web port inside the container was the default 8000.

We then looked at the site cookies in the browser:

    cval
    session_id_8000
    session_id_8001
    splunkd_8000
    splunkd_8001
    splunkweb_csrf_token_8000
    splunkweb_csrf_token_8001
    splunkweb_uid

**Note:** In case it's significant, both of these Splunk instances are using the Free license.

Only `cval` and `splunkweb_uid` are without port-specific qualifiers.

So far, so good: neither instance of Splunk Web has displayed the dreaded "Your session has expired" message. I'll report back here again if it happens.

Could you please update that table of environment variables to include `SPLUNK_HTTP_PORT`.

With sincere thanks to my colleague (you know who you are 😉 ).
