### ISSUE TITLE
Use submodules rather than clone and gitignore for ansible upstream

### ISSUE THREAD

**Issue by ryanfaircloth** [splunk/docker-splunk#69]

**Comment by lephino** [comment]
The clone is left that way to allow easier changing of branch used by the upstream ci/cd system.  It allows the make var to be set instead of needing the hash / sha to be set on the module init.  Not sure we'll change to sub modules.  Any real reason for the request?

**Comment by ryanfaircloth** [comment]
My reasons are transparency, both through web UI and the directory structure the external repository inclusion is obvious unless you get into how the make and images work the external code and any risks are not really transparent.

**Comment by arctan5x** [comment]
@rfaircloth-splunk  @lephino 

We probably won't be including this change. Closing this for now. If this issue becomes critical, feel free to reopen and escalate to the dev team.
