### ISSUE TITLE
Recommended way to set *.conf files?

### ISSUE THREAD

**Issue by aegershman** [splunk/docker-splunk#71]
Currently I am using [docker-splunk-legacy using the `7.0.3-monitor` image](https://github.com/splunk/docker-splunk-legacy/tree/master/enterprise) as a standalone heavy-forwarder instance. I am creating my `*.conf` files (e.g., `props.conf`, `transforms.conf`, etc.) and mounting them as volumes within the heavy-forwarder container at `/var/opt/splunk/etc/system/local`.

I would like to use this new project. Is there a new better way to set these configuration files? I did not see anything in the [`ADVANCED.md`](https://github.com/splunk/docker-splunk/blob/develop/docs/ADVANCED.md#advanced-configurations) doc that suggested a better way to load things like `{props,transforms,inputs,outputs}.conf`.

Any advice is appreciated, thank you!

**Comment by lephino** [comment]
https://github.com/splunk/splunk-ansible/pull/30  -  This will go inside of the next version of the container we ship.
