### ISSUE TITLE
The user / perms model on develop is awkward

### ISSUE THREAD

**Issue by jmervine** [splunk/docker-splunk#81]
Hey,

I know you all are working on users, perms, etc. right now. My understanding is that on the current "develop" branch, `ansible` is the default user, which sudo's to `splunk` to set things up. This is fine, but it leaves manual interactions a bit awkward.

```
$ kc exec search-0 -- /opt/splunk/bin/splunk version
Splunk 7.2.1 (build be11b2c46e23)

Warning: cannot create "/opt/splunk/var/log/splunk"

Warning: cannot create "/opt/splunk/var/log/introspection"

Warning: cannot create "/opt/splunk/var/log/watchdog"
$ kubectl exec search-0 -- whoami
ansible
$ kubectl exec search-0 -- sudo -u splunk /opt/splunk/bin/splunk version
Splunk 7.2.1 (build be11b2c46e23)
```

This is certainly not a deal breaker, but I thought I'd raise it as an issue while you're still working things out.

Cheers!

**Comment by arctan5x** [comment]
Yeah. We strongly advise to sudo into Splunk user to interact with Splunk. Docker doesn't really provide a good way to switch a default user during the entrypoint, so if you have any suggestions I would be happy to hear!

**Comment by jmervine** [comment]
I don't have any clean suggestions that support moving to using an ansible users, as you've decided to do. To be honest, it's the same issue as if `root` were the default user, so perhaps I'm being a bit pedantic here. Apologies.

/close

**Comment by arctan5x** [comment]
No worries. The current battle is security vs ease of usability. Hard to draw the line in the middle :)
