### ISSUE TITLE
Unable to use Indexer Discovery to configure indexers

### ISSUE THREAD

**Issue by speshak** [splunk/docker-splunk#89]
I would like to wire the forwarder up to an indexing cluster using [indexer discovery](https://docs.splunk.com/Documentation/Splunk/7.2.0/Indexer/indexerdiscovery) but there doesn't appear to be a way to supply that configuration to the container.

**Comment by nwang92** [comment]
I thought we did this for the heavy forwarder + universal forwarder, but it looks like we don't. I think I'll fix this section with the following guidelines in order of precedence:
- For both heavy_forwarder + universal_forwarder roles, if `SPLUNK_CLUSTER_MASTER_URL` is provided, it will try to forward data using indexer discovery to the cluster master
- For both heavy_forwarder + universal_forwarder roles, if `SPLUNK_INDEXER_URL` is provided (when indexers are clustered or not), it will forward directly to indexers
- For both heavy_forwarder + universal_forwarder roles, if `SPLUNK_STANDALONE_URL` is provided, it will forward directly to indexers
