### ISSUE TITLE
Allow to use wildcards for SPLUNK_LICENSE_URI

### ISSUE THREAD

**Issue by outcoldman** [splunk/docker-splunk#91]
With the old version of Splunk container, I could install multiple Splunk licenses from the same folder by using a wildcard, see https://github.com/outcoldsolutions/splunk-app-boilerplate/blob/a73e6238f299c0c4c7e18177df64d30904529b5e/Makefile#L27

```
--env "SPLUNK_CMD=add licenses -auth admin:${SPLUNK_PASSWORD} /hack/splunk/licenses/*.lic || true" \
```

It will be good to have the same ability for when you target local folder with  `SPLUNK_LICENSE_URI`, like

```
"SPLUNK_LICENSE_URI=/hack/splunk/licenses/*.lic"
```

**Comment by arctan5x** [comment]
https://github.com/splunk/splunk-ansible/pull/96

The PR is pending.

**Comment by arctan5x** [comment]
Above PR will be merged in for the next release so closing this issue.
