### ISSUE TITLE
Capability to specify user-prefs.conf for admin user

### ISSUE THREAD

**Issue by outcoldman** [splunk/docker-splunk#93]
I see that I can add a `conf` in the `defaults.yml`, but it is pretty limited, as it writes configurations only to `server/local/*.conf`. 
I want to be able to write a configuration for the admin user, which should go to the `$SPLUNK_ETC/users/admin/user-prefs/local/user-prefs.conf`, something like

```
[general]
default_namespace = appboilerplate
search_use_advanced_editor = true
search_line_numbers = false
search_auto_format = false
search_syntax_highlighting = dark
# tz = America/Los_Angeles
```

**Comment by nwang92** [comment]
Closing in duplication of the overall feature request here: https://github.com/splunk/docker-splunk/issues/94
