### ISSUE TITLE
Write configurations to the apps/{app_name}/local

### ISSUE THREAD

**Issue by outcoldman** [splunk/docker-splunk#94]
Is there are any capability to write a configuration to not `system/local` path?

I am trying to solve simple scenario, write to the `$SPLUNK_ETC/apps/splunk_instrumentation/local/telemetry.conf`

```
[general]
optInVersionAcknowledged = 3
showOptInModal = 0
```

**Comment by nwang92** [comment]
I'm going to chalk https://github.com/splunk/docker-splunk/issues/93 and this issue up to the same feature request:
* Support the ability to create multiple named config files (filename explicitly specified by the user) with any contents (completely user-defined) on any location of the container's filesystem (again, user-specified)

I'm not sure we can accomplish all of this via container env vars, but we can definitely support this if you create your container using settings from the `default.yml` file. Going to close #93 if that's ok with you, but I'll get this into the next release (7.2.5).
