### ISSUE TITLE
Error add new app JMS Messaging Modular Input

### ISSUE THREAD

**Issue by jasonhue8183** [splunk/docker-splunk#97]
Hi,

i having error below after installed app JMS Messaging Modular Input from file  :

`Unable to initialize modular input "jms" defined inside the app "jms_ta": Introspecting scheme=jms: script running failed (exited with code 1).`

Appreciate for any advice.

Thanks
Jason

**Comment by nwang92** [comment]
What's the app + version you have installed? Is this from Splunkbase? You may also have success in troubleshooting what went wrong with that modinput if you search for `index=_internal` logs within your Splunk instance.

**Comment by jasonhue8183** [comment]
Hi @nwang92 ,

Downloaded Splunk JMS Modular Input v1.6.1 from splunkbase. I installed from file. 
I cannot find JMS Messaging listed in Splunk Data Inputs after restart container and with error above .

Appreciate for any advice.

Thanks
Jason

**Comment by jasonhue8183** [comment]
I try installed from file or manually untar downloaded file to the mount folder  /opt/splunk/etc/apps still having the same error 

`Unable to initialize modular input "jms" defined inside the app "jms_ta": Introspecting scheme=jms: script running failed (exited with code 1).`

**Comment by nwang92** [comment]
Hey Jason,

I did some more investigation on this and I'm able to reproduce your error. For some background: modinputs generally have some schema which get validated when Splunk starts. You can actually simulate what the scheme looks like with something like: `/opt/splunk/bin/splunk cmd python /opt/splunk/etc/apps/jms_ta/bin/jms.py --scheme`, which should dump a large xml blob.

When I ran the command above, I also got an error, which is likely what Splunk is upset about. Specifically, my error was:
```
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/jms_ta/bin/jms.py", line 120, in <module>
    do_scheme()
  File "/opt/splunk/etc/apps/jms_ta/bin/jms.py", line 50, in do_scheme
    run_java()
  File "/opt/splunk/etc/apps/jms_ta/bin/jms.py", line 98, in run_java
    process = Popen(java_args)
  File "/opt/splunk/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/opt/splunk/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

It looks like the JMS modinput requires java to run, and without it, it will fail to do anything. At the moment, we don't support native Java installation with this docker image, although you could inherit this image and install it yourself. Out of curiosity, do you know what java version you plan on using? We're looking to incorporate a flag or option to include java, but it would likely be limited to only specific versions.

**Comment by jasonhue8183** [comment]
Hi @nwang92,

Appreciate for the prompt response. We prefer Java 8.

Thank you.
Jason

**Comment by matthewmodestino** [comment]
I would suggest both java 8 and open-jdk as we have apps that call for both (ITSI and DBconnect).

**Comment by arctan5x** [comment]
There is a PR pending to support Oracle Java 8 and Oracle Java 11.

**Comment by nwang92** [comment]
Java support has been added here: https://github.com/splunk/splunk-ansible/pull/60

This should be out with the next maintenance release of Splunk (7.2.4)
